My Project: examples/_ddigitalbutton/arduino-vscode-one-button-menu/src/main.cpp File Reference
main.cpp File Reference
#include "Arduino.h"
#include <DMenu.h>
#include <U8x8lib.h>
#include <DDigitalButton.h>
Macros
#define WIDTH 16
#define HEIGHT 8
Functions
DMenu * CreateMainMenu (void)
DMenu * CreateSubMenu1 (void)
DMenu * CreateSubMenu2 (void)
void PrintMenu (DMenu *Menu, uint8_t X=0, uint8_t Y=0)
void Debug (const String &msg)
U8X8_SSD1306_128X64_NONAME_HW_I2C u8x8 (U8X8_PIN_NONE)
void setup ()
void loop ()
Variables
DDigitalButton * Button =NULL
DMenu * CurrMenu =NULL
Macro Definition Documentation
HEIGHT
#define HEIGHT 8
Definition at line 7 of file main.cpp.
WIDTH
#define WIDTH 16
Definition at line 6 of file main.cpp.
Function Documentation
CreateMainMenu()
DMenu * CreateMainMenu (void)
Definition at line 96 of file main.cpp.
References DMenu::AddItem(), CurrMenu, and DMenu::Loop.
Referenced by loop(), and setup().
CreateSubMenu1()
DMenu * CreateSubMenu1 (void)
Definition at line 111 of file main.cpp.
References DMenu::AddItem(), CurrMenu, and DMenu::Loop.
Referenced by loop().
CreateSubMenu2()
DMenu * CreateSubMenu2 (void)
Definition at line 126 of file main.cpp.
References DMenu::AddItem(), CurrMenu, and DMenu::Loop.
Referenced by loop().
Debug()
void Debug (const String & msg)
Definition at line 179 of file main.cpp.
Referenced by loop(), and setup().
loop()
void loop ()
Definition at line 42 of file main.cpp.
References Button, CreateMainMenu(), CreateSubMenu1(), CreateSubMenu2(), CurrMenu, DDigitalButton::DBL_PRESSED, DDigitalButton::DBL_PRESSING, Debug(), DMenu::Down(), DMenu::GetName(), DDigitalButton::LONG_PRESSED, DDigitalButton::LONG_PRESSING, DDigitalButton::PRESS, DDigitalButton::PRESSED, PrintMenu(), DDigitalButton::Read(), DDigitalButton::RELEASE, DDigitalButton::RELEASED, and DMenu::Select().
PrintMenu()
void PrintMenu (DMenu * Menu, uint8_t X = 0, uint8_t Y = 0)
Definition at line 141 of file main.cpp.
References CurrMenu, DMenu::GetCurrItemIndex(), DMenu::GetItem(), DMenu::GetItemsCount(), DMenu::GetName(), u8x8(), and WIDTH.
Referenced by loop(), and setup().
setup()
void setup ()
Definition at line 22 of file main.cpp.
References Button, CreateMainMenu(), CurrMenu, Debug(), PrintMenu(), and u8x8().
u8x8()
U8X8_SSD1306_128X64_NONAME_HW_I2C u8x8 (U8X8_PIN_NONE)
Referenced by PrintMenu(), and setup().
Variable Documentation
Button
DDigitalButton* Button =NULL
Definition at line 18 of file main.cpp.
Referenced by DCMotorRunTest(), loop(), ServoRunTest(), and setup().
CurrMenu
DMenu* CurrMenu =NULL
Definition at line 20 of file main.cpp.
Referenced by CreateMainMenu(), CreateSubMenu1(), CreateSubMenu2(), loop(), MenuDCMotorSetup(), MenuDCMotorSetupPin(), MenuMain(), MenuMotor(), MenuServoSetup(), PrintMenu(), and setup().