My Project: examples/_dhtxx/rpi-dhtxx-demo/main.cpp File Reference
main.cpp File Reference
#include <iostream>
#include <dhtxx>
Functions
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 6 of file main.cpp.
References DHTXX::begin(), delay(), DHTXX::DHT_11, DGpioChip::getInfo(), DHTXX::getLastError(), DGpioChip::getLastError(), DGpioChip::handle(), DHTXX::humidity, DGpioChip::isReady(), DHTXX::read(), and DHTXX::temp.