My Project: examples/_dmpacket/main.cpp File Reference
main.cpp File Reference
#include <iostream>
#include "BotCommands.h"
#include "DMPacket.h"
#include <boost/asio.hpp>
Functions
int Send (boost::asio::ip::tcp::socket &Socket, DMPacket &Packet)
int Recv (boost::asio::ip::tcp::socket &Socket, DMPacket &Packet)
int main ()
Function Documentation
main()
int main ()
Definition at line 34 of file main.cpp.
References DMPacket::ReadDWord(), DMPacket::ReadFloat(), DMPacket::ReadInt16(), and DMPacket::ReadWord().
Recv()
int Recv (boost::asio::ip::tcp::socket & Socket, DMPacket & Packet)
Definition at line 18 of file main.cpp.
Send()
int Send (boost::asio::ip::tcp::socket & Socket, DMPacket & Packet)
Definition at line 8 of file main.cpp.
References DMPacket::Size().