My Project: examples/_mega-demo/src/main.cpp File Reference
main.cpp File Reference
#include "Arduino.h"
#include <string>
#include <dmenu>
#include <ddigitalbutton>
#include <dservo>
#include <ddcmotor>
#include <oled.h>
Macros
#define COLS 16
#define ROWS 8
#define STR_MAIN_MENU "Main Menu"
#define ID_MAIN_MENU 0
#define STR_SERVO_MAIN "Servo Test"
#define ID_SERVO_MAIN 10
#define STR_SERVO_SETUP "Servo Setup"
#define ID_SERVO_SETUP 11
#define STR_SERVO_RUN "Servo Run"
#define ID_SERVO_RUN 12
#define STR_DCMOTOR_MAIN "DC Motor Test"
#define ID_DCMOTOR_MAIN 20
#define STR_STEPPER_MAIN "Stepper Test"
#define ID_STEPPER_MAIN 30
#define STR_START "Start"
#define ID_START 40
#define STR_SETUP "Setup"
#define ID_SETUP 41
#define STR_BACK "Back"
#define ID_BACK 42
#define STR_PIN_UP "Inc pin nr"
#define ID_PIN_UP 43
#define STR_PIN_DOWN "Dec pin nr"
#define ID_PIN_DOWN 44
Functions
DMenu * MenuMain (void)
DMenu * MenuMotor (std::string Title, int ID)
DMenu * MenuServoSetup (void)
DMenu * MenuDCMotorSetup (void)
void PrintMenu (DMenu *Menu, uint8_t Col=0, uint8_t Row=0)
void Debug (const String &msg)
void ServoRunTest (void)
void DCMotorRunTest (void)
OLED display (18, 19, NO_RESET_PIN, OLED::W_128, OLED::H_64, OLED::CTRL_SSD1306, 0x3C)
void setup ()
void loop ()
DMenu * MenuDCMotorSetupPin (uint8_t Pin)
Variables
DDigitalButton * Button =nullptr
uint8_t ServoPin =PB1
DServo * Servo =nullptr
uint8_t DCMotorPin1 =PB2
uint8_t DCMotorPin2 =PB3
DDCMotor * DCMotor =nullptr
DMenu * CurrMenu =nullptr
Macro Definition Documentation
COLS
#define COLS 16
Definition at line 9 of file main.cpp.
ID_BACK
#define ID_BACK 42
Definition at line 33 of file main.cpp.
ID_DCMOTOR_MAIN
#define ID_DCMOTOR_MAIN 20
Definition at line 23 of file main.cpp.
ID_MAIN_MENU
#define ID_MAIN_MENU 0
Definition at line 13 of file main.cpp.
ID_PIN_DOWN
#define ID_PIN_DOWN 44
Definition at line 38 of file main.cpp.
ID_PIN_UP
#define ID_PIN_UP 43
Definition at line 36 of file main.cpp.
ID_SERVO_MAIN
#define ID_SERVO_MAIN 10
Definition at line 16 of file main.cpp.
ID_SERVO_RUN
#define ID_SERVO_RUN 12
Definition at line 20 of file main.cpp.
ID_SERVO_SETUP
#define ID_SERVO_SETUP 11
Definition at line 18 of file main.cpp.
ID_SETUP
#define ID_SETUP 41
Definition at line 31 of file main.cpp.
ID_START
#define ID_START 40
Definition at line 29 of file main.cpp.
ID_STEPPER_MAIN
#define ID_STEPPER_MAIN 30
Definition at line 26 of file main.cpp.
ROWS
#define ROWS 8
Definition at line 10 of file main.cpp.
STR_BACK
#define STR_BACK "Back"
Definition at line 32 of file main.cpp.
STR_DCMOTOR_MAIN
#define STR_DCMOTOR_MAIN "DC Motor Test"
Definition at line 22 of file main.cpp.
STR_MAIN_MENU
#define STR_MAIN_MENU "Main Menu"
Definition at line 12 of file main.cpp.
STR_PIN_DOWN
#define STR_PIN_DOWN "Dec pin nr"
Definition at line 37 of file main.cpp.
STR_PIN_UP
#define STR_PIN_UP "Inc pin nr"
Definition at line 35 of file main.cpp.
STR_SERVO_MAIN
#define STR_SERVO_MAIN "Servo Test"
Definition at line 15 of file main.cpp.
STR_SERVO_RUN
#define STR_SERVO_RUN "Servo Run"
Definition at line 19 of file main.cpp.
STR_SERVO_SETUP
#define STR_SERVO_SETUP "Servo Setup"
Definition at line 17 of file main.cpp.
STR_SETUP
#define STR_SETUP "Setup"
Definition at line 30 of file main.cpp.
STR_START
#define STR_START "Start"
Definition at line 28 of file main.cpp.
STR_STEPPER_MAIN
#define STR_STEPPER_MAIN "Stepper Test"
Definition at line 25 of file main.cpp.
Function Documentation
DCMotorRunTest()
void DCMotorRunTest (void)
Definition at line 330 of file main.cpp.
References DDCMotor::attach(), DDCMotor::attached(), Button, DCMotor, DCMotorPin1, DCMotorPin2, DServo::detach(), display(), millis(), DDigitalButton::PRESSED, DDCMotor::PWM_PWM, DDigitalButton::Read(), and Servo.
Referenced by loop().
Debug()
void Debug (const String & msg)
Definition at line 417 of file main.cpp.
display()
OLED display (18 , 19 , NO_RESET_PIN , OLED::W_128 , OLED::H_64 , OLED::CTRL_SSD1306 , 0x3C)
Referenced by DCMotorRunTest(), PrintMenu(), ServoRunTest(), and setup().
loop()
void loop ()
Definition at line 97 of file main.cpp.
References Button, CurrMenu, DCMotor, DCMotorPin1, DCMotorPin2, DCMotorRunTest(), DMenu::Down(), DMenu::GetID(), ID_BACK, ID_DCMOTOR_MAIN, ID_PIN_DOWN, ID_PIN_UP, ID_SERVO_MAIN, ID_SERVO_RUN, ID_SERVO_SETUP, ID_SETUP, ID_START, ID_STEPPER_MAIN, DDigitalButton::LONG_PRESSED, MenuDCMotorSetup(), MenuMain(), MenuMotor(), MenuServoSetup(), DDigitalButton::PRESSED, PrintMenu(), DDigitalButton::Read(), DMenu::Select(), Servo, ServoPin, ServoRunTest(), STR_DCMOTOR_MAIN, STR_SERVO_MAIN, and STR_STEPPER_MAIN.
MenuDCMotorSetup()
DMenu * MenuDCMotorSetup (void)
Definition at line 296 of file main.cpp.
References DMenu::AddItem(), CurrMenu, ID_BACK, DMenu::Loop, and STR_BACK.
Referenced by loop().
MenuDCMotorSetupPin()
DMenu* MenuDCMotorSetupPin (uint8_t Pin)
Definition at line 313 of file main.cpp.
References DMenu::AddItem(), CurrMenu, ID_BACK, ID_PIN_DOWN, ID_PIN_UP, DMenu::Loop, STR_BACK, STR_PIN_DOWN, and STR_PIN_UP.
MenuMain()
DMenu * MenuMain (void)
Definition at line 206 of file main.cpp.
References DMenu::AddItem(), CurrMenu, ID_DCMOTOR_MAIN, ID_MAIN_MENU, ID_SERVO_MAIN, ID_STEPPER_MAIN, DMenu::Loop, STR_DCMOTOR_MAIN, STR_MAIN_MENU, STR_SERVO_MAIN, and STR_STEPPER_MAIN.
Referenced by loop(), and setup().
MenuMotor()
DMenu * MenuMotor (std::string Title, int ID)
Definition at line 222 of file main.cpp.
References DMenu::AddItem(), CurrMenu, ID_BACK, ID_SETUP, ID_START, DMenu::Loop, STR_BACK, STR_SETUP, and STR_START.
Referenced by loop().
MenuServoSetup()
DMenu * MenuServoSetup (void)
Definition at line 242 of file main.cpp.
References DMenu::AddItem(), CurrMenu, ID_BACK, ID_PIN_DOWN, ID_PIN_UP, ID_SERVO_SETUP, DMenu::Loop, STR_BACK, STR_PIN_DOWN, STR_PIN_UP, and STR_SERVO_SETUP.
Referenced by loop().
PrintMenu()
void PrintMenu (DMenu * Menu, uint8_t Col = 0, uint8_t Row = 0)
Definition at line 365 of file main.cpp.
References COLS, CurrMenu, display(), DMenu::GetCurrItemIndex(), DMenu::GetID(), DMenu::GetItem(), DMenu::GetItemsCount(), DMenu::GetName(), ID_SERVO_RUN, ID_SERVO_SETUP, DServo::read(), Servo, and ServoPin.
ServoRunTest()
void ServoRunTest (void)
Definition at line 259 of file main.cpp.
References DServo::attached(), Button, DServo::detach(), display(), millis(), DDigitalButton::PRESSED, DDigitalButton::Read(), Servo, ServoPin, and DServo::writeMicroseconds().
Referenced by loop().
setup()
void setup ()
Definition at line 78 of file main.cpp.
References Button, CurrMenu, display(), MenuMain(), and PrintMenu().
Variable Documentation
Button
DDigitalButton* Button =nullptr
Definition at line 61 of file main.cpp.
CurrMenu
DMenu* CurrMenu =nullptr
Definition at line 76 of file main.cpp.
DCMotor
DDCMotor* DCMotor =nullptr
Definition at line 70 of file main.cpp.
Referenced by DCMotorRunTest(), and loop().
DCMotorPin1
uint8_t DCMotorPin1 =PB2
Definition at line 68 of file main.cpp.
Referenced by DCMotorRunTest(), and loop().
DCMotorPin2
uint8_t DCMotorPin2 =PB3
Definition at line 69 of file main.cpp.
Referenced by DCMotorRunTest(), and loop().
Servo
DServo* Servo =nullptr
Definition at line 65 of file main.cpp.
Referenced by DCMotorRunTest(), loop(), PrintMenu(), ServoRunTest(), and setup().
ServoPin
uint8_t ServoPin =PB1
Definition at line 64 of file main.cpp.
Referenced by loop(), PrintMenu(), and ServoRunTest().