My Project: DI2CMaster Class Reference
DI2CMaster Class Reference
#include <di2cmaster.h>
Public Member Functions
DI2CMaster (DI2CBusHandle i2cBusHandle, uint16_t i2cMaxBufferLenght=0)
Construct a new DI2CMaster::DI2CMaster object.
~DI2CMaster ()
bool isReady (void)
std::string getLastError (void)
bool writeByte (uint8_t slaveAddr, uint8_t cmdReg, uint8_t data)
Write a BYTE at specified i2c register of the slave device.
bool writeWord (uint8_t slaveAddr, uint8_t cmdReg, uint16_t data)
Write a WORD (2 bytes) at specified i2c register of the slave device.
bool writeBuf (uint8_t slaveAddr, uint8_t cmdReg, uint8_t *writeBuffer, uint16_t writeLen)
Write a BUFFER at specified i2c register of the slave device.
uint8_t recvByte (uint8_t slaveAddr)
Read a BYTE from an i2c slave device.
uint16_t recvWord (uint8_t slaveAddr)
Read a WORD(2 bytes) from an i2c slave device.
bool recvBuf (uint8_t slaveAddr, uint8_t *recvBuf, uint16_t recvLen)
Read a BUFFER from an i2c slave device.
uint8_t askForByte (uint8_t slaveAddr, uint8_t cmdReg)
Read a BYTE from specified i2c register of the slave device.
uint16_t askForWord (uint8_t slaveAddr, uint8_t cmdReg)
Read a WORD from specified i2c register of the slave device.
bool askForBuf (uint8_t slaveAddr, uint8_t cmdReg, uint8_t *recvBuf, uint16_t recvLen)
Read a BUFFER from specified i2c register of the slave device.
bool sendByte (uint8_t slaveAddr, uint8_t data)
Send a BYTE to a slave device.
bool sendWord (uint8_t slaveAddr, uint16_t data)
Send a WORD (2 bytes) to a slave device.
bool sendBuf (uint8_t slaveAddr, uint8_t *data, uint16_t dataLen)
Send a BUFFER to a slave device.
Private Attributes
DI2CBusHandle busHandle
std::string lastErrorString
size_t maxBufLenght
Detailed Description
Definition at line 8 of file di2cmaster.h.
Constructor & Destructor Documentation
DI2CMaster()
DI2CMaster::DI2CMaster (DI2CBusHandle i2cBusHandle, uint16_t i2cMaxBufferLenght = 0)
Construct a new DI2CMaster::DI2CMaster object.
Parameters
i2cBusHandle -> an handle for the i2c bus (can obtained by DI2CBus() class).
i2cMaxBufferLenght -> max lenght of tx buffer used in each transaction.
If value is 0, no limit are set.
If value is greater than 0, write...() and askFor...() API truncate buffer of each transaction to this value, send...() API do as many transaction as need to send all data.
Definition at line 58 of file di2cmaster.cpp.
References busHandle, and maxBufLenght.
~DI2CMaster()
DI2CMaster::~DI2CMaster ()
Definition at line 64 of file di2cmaster.cpp.
Member Function Documentation
askForBuf()
bool DI2CMaster::askForBuf (uint8_t slaveAddr, uint8_t cmdReg, uint8_t * recvBuffer, uint16_t recvLen)
Read a BUFFER from specified i2c register of the slave device.
...that means "send 1 command byte and read N bytes"...
Parameters
slaveAddr -> i2c slave device address.
cmdReg -> i2c device command (aka register).
Returns
true on success, otherwise false (you can retrive the error by calling getLastError()).
Definition at line 361 of file di2cmaster.cpp.
References busHandle, lastErrorString, and maxBufLenght.
Referenced by INA228::charge(), INA228::current(), INA228::energy(), INA228::power(), INA228::shuntvoltage(), and INA228::voltage().
askForByte()
uint8_t DI2CMaster::askForByte (uint8_t slaveAddr, uint8_t cmdReg)
Read a BYTE from specified i2c register of the slave device.
...that means "send 1 command byte and read 1 byte"...
Parameters
slaveAddr -> i2c slave device address.
cmdReg -> i2c device command (aka register).
Returns
BYTE value read. If returned vaue is 0xFF can be that something was wrong.
Definition at line 297 of file di2cmaster.cpp.
References busHandle, lastErrorString, and recvByte().
askForWord()
uint16_t DI2CMaster::askForWord (uint8_t slaveAddr, uint8_t cmdReg)
Read a WORD from specified i2c register of the slave device.
...that means "send 1 command byte and read 2 bytes"...
Parameters
slaveAddr -> i2c slave device address.
cmdReg -> i2c device command (aka register).
Returns
WORD value read. If returned vaue is 0xFFFF can be that something was wrong.
Definition at line 329 of file di2cmaster.cpp.
References busHandle, lastErrorString, recvWord(), and WORD.
Referenced by INA226::current(), INA228::dietemp(), INA226::getInfo(), INA228::getInfo(), INA226::power(), and INA226::voltage().
getLastError()
std::string DI2CMaster::getLastError (void)
Returns
last result of io operation.
Definition at line 79 of file di2cmaster.cpp.
References lastErrorString.
Referenced by main().
isReady()
bool DI2CMaster::isReady (void)
Returns
true if there is a bus handle valid.
Definition at line 71 of file di2cmaster.cpp.
References busHandle.
recvBuf()
bool DI2CMaster::recvBuf (uint8_t slaveAddr, uint8_t * recvBuffer, uint16_t recvLen)
Read a BUFFER from an i2c slave device.
Parameters
slaveAddr -> i2c slave device address.
recvBuffer -> pointer to a buffer for received data.
recvLen -> lenght of data to read.
Returns
true on success, otherwise false (you can retrive the error by calling getLastError()).
Definition at line 259 of file di2cmaster.cpp.
References busHandle, lastErrorString, and maxBufLenght.
recvByte()
uint8_t DI2CMaster::recvByte (uint8_t slaveAddr)
Read a BYTE from an i2c slave device.
Parameters
slaveAddr -> i2c slave device address.
Returns
BYTE value read. If returned vaue is 0xFF can be that something was wrong.
Definition at line 203 of file di2cmaster.cpp.
References busHandle, and lastErrorString.
Referenced by askForByte().
recvWord()
uint16_t DI2CMaster::recvWord (uint8_t slaveAddr)
Read a WORD(2 bytes) from an i2c slave device.
Parameters
slaveAddr -> i2c slave device address.
Returns
WORD value read. If returned value is 0xFFFF can be that something was wrong.
Definition at line 230 of file di2cmaster.cpp.
References busHandle, lastErrorString, and WORD.
Referenced by askForWord().
sendBuf()
bool DI2CMaster::sendBuf (uint8_t slaveAddr, uint8_t * data, uint16_t dataLen)
Send a BUFFER to a slave device.
Parameters
slaveAddr -> i2c slave device address.
data -> buffer to send.
dataLen -> the lenght of the buffer.
Returns
true on success, otherwise false (you can retrive the error by calling getLastError()).
Definition at line 460 of file di2cmaster.cpp.
References busHandle, lastErrorString, and maxBufLenght.
Referenced by main(), writeBuf(), writeByte(), and writeWord().
sendByte()
bool DI2CMaster::sendByte (uint8_t slaveAddr, uint8_t data)
Send a BYTE to a slave device.
Parameters
slaveAddr -> i2c slave device address.
data -> the byte to send.
Returns
true on success, otherwise false (you can retrive the error by calling getLastError()).
Definition at line 400 of file di2cmaster.cpp.
References busHandle, and lastErrorString.
sendWord()
bool DI2CMaster::sendWord (uint8_t slaveAddr, uint16_t data)
Send a WORD (2 bytes) to a slave device.
Parameters
slaveAddr -> i2c slave device address.
data -> the word to send.
Returns
true on success, otherwise false (you can retrive the error by calling getLastError()).
Definition at line 428 of file di2cmaster.cpp.
References busHandle, HIBYTE, lastErrorString, and LOBYTE.
writeBuf()
bool DI2CMaster::writeBuf (uint8_t slaveAddr, uint8_t cmdReg, uint8_t * data, uint16_t dataLen)
Write a BUFFER at specified i2c register of the slave device.
...that means "send 1 command byte followed by N data bytes"...
Parameters
slaveAddr -> i2c slave device address.
cmdReg -> i2c device command (aka register).
data -> the buffer to send.
dataLen -> the lenght of the buffer.
Returns
true on success, otherwise false (you can retrive the error by calling getLastError()).
Definition at line 164 of file di2cmaster.cpp.
References busHandle, lastErrorString, maxBufLenght, and sendBuf().
writeByte()
bool DI2CMaster::writeByte (uint8_t slaveAddr, uint8_t cmdReg, uint8_t data)
Write a BYTE at specified i2c register of the slave device.
...that means "send 1 command byte followed by 1 data byte"...
Parameters
slaveAddr -> i2c slave device address.
cmdReg -> i2c device command (aka register).
data -> the byte to send.
Returns
true on success, otherwise false (you can retrive the error by calling getLastError()).
Definition at line 93 of file di2cmaster.cpp.
References busHandle, lastErrorString, and sendBuf().
writeWord()
bool DI2CMaster::writeWord (uint8_t slaveAddr, uint8_t cmdReg, uint16_t data)
Write a WORD (2 bytes) at specified i2c register of the slave device.
...that means "send 1 command byte followed by 2 data bytes"...
Parameters
slaveAddr -> i2c slave device address.
cmdReg -> i2c device command (aka register).
data -> the WORD to send.
Returns
true on success, otherwise false (you can retrive the error by calling getLastError()).
Definition at line 128 of file di2cmaster.cpp.
References busHandle, HIBYTE, lastErrorString, LOBYTE, and sendBuf().
Referenced by INA226::begin(), and INA228::begin().
Member Data Documentation
busHandle
DI2CBusHandle DI2CMaster::busHandle private
Definition at line 37 of file di2cmaster.h.
Referenced by askForBuf(), askForByte(), askForWord(), DI2CMaster(), isReady(), recvBuf(), recvByte(), recvWord(), sendBuf(), sendByte(), sendWord(), writeBuf(), writeByte(), and writeWord().
lastErrorString
std::string DI2CMaster::lastErrorString private
Definition at line 38 of file di2cmaster.h.
Referenced by askForBuf(), askForByte(), askForWord(), getLastError(), recvBuf(), recvByte(), recvWord(), sendBuf(), sendByte(), sendWord(), writeBuf(), writeByte(), and writeWord().
maxBufLenght
size_t DI2CMaster::maxBufLenght private
Definition at line 39 of file di2cmaster.h.
Referenced by askForBuf(), DI2CMaster(), recvBuf(), sendBuf(), and writeBuf().
The documentation for this class was generated from the following files:
src/di2c/di2cmaster.h
src/di2c/di2cmaster.cpp