My Project: DDigitalOutput Class Reference
DDigitalOutput Class Reference
#include <ddigitaloutput.h>
Public Member Functions
DDigitalOutput (int digitalPin, DGpioHandle gpioHandle=-1)
~DDigitalOutput ()
Destroy the DDigitalOutput::DDigitalOutput object and free pin use.
bool begin (int initialLevel=LOW)
int read (void)
Legge lo stato del pin.
int write (int level)
Uso interno: Setta il pin di uscita al livello logico richiesto.
void high (void)
Porta il pin di uscita a livello logico 1 (5V)
void low (void)
Imposta il pin di uscita a livello logico 0 (GND)
void toggle (void)
Cambia lo stato del pin di uscita.
int getPin (void)
bool isAttached (void)
std::string getLastError (void)
operator int ()
overload operatore ==
DDigitalOutput & operator= (bool level)
overload operatore =
Private Attributes
int pin
bool currLevel
DGpioHandle handle
DResult lastResult
Detailed Description
Definition at line 13 of file ddigitaloutput.h.
Constructor & Destructor Documentation
DDigitalOutput()
DDigitalOutput::DDigitalOutput (int digitalPin, DGpioHandle gpioHandle = -1)
Parameters
DigitalPin -> pin da utilizzare come output
InitialState -> Stato logico iniziale da attivare: [HIGH,LOW] oppure [1,0]
Definition at line 45 of file ddigitaloutput.cpp.
References currLevel, DERR_CLASS_NOT_BEGUN, DERR_GPIO_NOT_READY, handle, initGpio(), isGpioReady(), lastResult, LOW, and pin.
~DDigitalOutput()
DDigitalOutput::~DDigitalOutput ()
Destroy the DDigitalOutput::DDigitalOutput object and free pin use.
Definition at line 71 of file ddigitaloutput.cpp.
References handle, pin, and releasePin().
Member Function Documentation
begin()
bool DDigitalOutput::begin (int initialLevel = LOW)
Definition at line 76 of file ddigitaloutput.cpp.
References currLevel, DRES_OK, handle, initPin(), lastResult, NO_FLAGS, OUTPUT, pin, and write().
Referenced by main().
getLastError()
std::string DDigitalOutput::getLastError (void)
Definition at line 163 of file ddigitaloutput.cpp.
References getErrorCode(), and lastResult.
getPin()
int DDigitalOutput::getPin (void)
Returns
input pin number.
Definition at line 153 of file ddigitaloutput.cpp.
References pin.
high()
void DDigitalOutput::high (void)
Porta il pin di uscita a livello logico 1 (5V)
Definition at line 93 of file ddigitaloutput.cpp.
References HIGH, and write().
isAttached()
bool DDigitalOutput::isAttached (void)
Definition at line 158 of file ddigitaloutput.cpp.
References DRES_OK, and lastResult.
low()
void DDigitalOutput::low (void)
Imposta il pin di uscita a livello logico 0 (GND)
Definition at line 99 of file ddigitaloutput.cpp.
References LOW, and write().
operator int()
DDigitalOutput::operator int ()
overload operatore ==
Definition at line 111 of file ddigitaloutput.cpp.
operator=()
DDigitalOutput & DDigitalOutput::operator= (bool level)
overload operatore =
Definition at line 117 of file ddigitaloutput.cpp.
References write().
read()
int DDigitalOutput::read (void)
Legge lo stato del pin.
Returns
lo stato logico dell'ingresso: HIGH o LOW (negative value is error code). N.B. aggiorna currLevel.
Definition at line 128 of file ddigitaloutput.cpp.
References currLevel, DRES_OK, handle, lastResult, pin, and readPin().
toggle()
void DDigitalOutput::toggle (void)
Cambia lo stato del pin di uscita.
Definition at line 105 of file ddigitaloutput.cpp.
References currLevel, and write().
write()
int DDigitalOutput::write (int level)
Uso interno: Setta il pin di uscita al livello logico richiesto.
Parameters
State -> Il livello logico da impostare [HIGH,LOW] oppure [1,0]
Definition at line 143 of file ddigitaloutput.cpp.
References currLevel, handle, lastResult, pin, and writePin().
Referenced by begin(), high(), low(), main(), operator=(), and toggle().
Member Data Documentation
currLevel
bool DDigitalOutput::currLevel private
Definition at line 34 of file ddigitaloutput.h.
Referenced by begin(), DDigitalOutput(), read(), toggle(), and write().
handle
DGpioHandle DDigitalOutput::handle private
Definition at line 37 of file ddigitaloutput.h.
Referenced by begin(), DDigitalOutput(), read(), write(), and ~DDigitalOutput().
lastResult
DResult DDigitalOutput::lastResult private
Definition at line 38 of file ddigitaloutput.h.
Referenced by begin(), DDigitalOutput(), getLastError(), isAttached(), read(), and write().
pin
int DDigitalOutput::pin private
Definition at line 33 of file ddigitaloutput.h.
Referenced by begin(), DDigitalOutput(), getPin(), read(), write(), and ~DDigitalOutput().
The documentation for this class was generated from the following files:
src/ddigitaloutput/ddigitaloutput.h
src/ddigitaloutput/ddigitaloutput.cpp