My Project: DDigitalInput Class Reference
DDigitalInput Class Reference
#include <ddigitalinput.h>
Public Member Functions
DDigitalInput (int digitalPin, DGpioHandle gpioHandle=-1)
~DDigitalInput ()
Destroy the DDigitalInput::DDigitalInput object and free pin use.
bool begin (bool pullUp=false, unsigned int msecDebounce=0)
bool isChanged (short int *newLevel=nullptr)
bool isChangedToLow (void)
Verifica se lo stato del pin è cambiato da HIGH in LOW rispetto all'ultimo controllo.
bool isChangedToHigh (void)
Verifica se lo stato del pin è cambiato da LOW in HIGH rispetto all'ultimo controllo.
bool isAttached (void)
int read (void)
Legge lo stato del pin.
int getPin (void)
std::string getLastError (void)
operator int ()
overload operatore ==
Private Attributes
int pin
int currLevel
int prevLevel
unsigned long currMsec
unsigned long prevMsec
unsigned long debounceMsec
DGpioHandle handle
DResult lastResult
Detailed Description
Definition at line 6 of file ddigitalinput.h.
Constructor & Destructor Documentation
DDigitalInput()
DDigitalInput::DDigitalInput (int digitalPin, DGpioHandle gpioHandle = -1)
Parameters
digitalPin -> pin da utilizzare come input
pullUp -> se true viene attivata la resistena interna di pull-up
Definition at line 44 of file ddigitalinput.cpp.
References currLevel, DERR_CLASS_NOT_BEGUN, DERR_GPIO_NOT_READY, handle, initGpio(), isGpioReady(), lastResult, LOW, pin, and prevLevel.
~DDigitalInput()
DDigitalInput::~DDigitalInput ()
Destroy the DDigitalInput::DDigitalInput object and free pin use.
Definition at line 71 of file ddigitalinput.cpp.
References handle, pin, and releasePin().
Member Function Documentation
begin()
bool DDigitalInput::begin (bool pullUp = false, unsigned int msecDebounce = 0)
Definition at line 76 of file ddigitalinput.cpp.
References currLevel, debounceMsec, DRES_OK, handle, initPin(), INPUT, INPUT_PULLUP, lastResult, millis(), NO_FLAGS, pin, prevLevel, prevMsec, and read().
Referenced by main().
getLastError()
std::string DDigitalInput::getLastError (void)
Definition at line 205 of file ddigitalinput.cpp.
References getErrorCode(), and lastResult.
Referenced by main().
getPin()
int DDigitalInput::getPin (void)
Returns
input pin number.
Definition at line 195 of file ddigitalinput.cpp.
References pin.
isAttached()
bool DDigitalInput::isAttached (void)
Definition at line 200 of file ddigitalinput.cpp.
References DRES_OK, and lastResult.
isChanged()
bool DDigitalInput::isChanged (short int * newLevel = nullptr)
Parameters
NewLevel -> Puntatore alla variabile che conterrà il nuovo stato (se null viene ignorata)
Returns
true se cambiato false se non cambiato
Definition at line 101 of file ddigitalinput.cpp.
References currLevel, currMsec, debounceMsec, millis(), prevLevel, prevMsec, and read().
Referenced by main().
isChangedToHigh()
bool DDigitalInput::isChangedToHigh (void)
Verifica se lo stato del pin è cambiato da LOW in HIGH rispetto all'ultimo controllo.
Returns
true se è cambiato in HIGH false se è non è cambiato
Definition at line 154 of file ddigitalinput.cpp.
References currLevel, currMsec, debounceMsec, HIGH, millis(), prevLevel, prevMsec, and read().
isChangedToLow()
bool DDigitalInput::isChangedToLow (void)
Verifica se lo stato del pin è cambiato da HIGH in LOW rispetto all'ultimo controllo.
Returns
true se è cambiato in LOW false se è non è cambiato
Definition at line 132 of file ddigitalinput.cpp.
References currLevel, currMsec, debounceMsec, LOW, millis(), prevLevel, prevMsec, and read().
operator int()
DDigitalInput::operator int ()
overload operatore ==
Definition at line 171 of file ddigitalinput.cpp.
read()
int DDigitalInput::read (void)
Legge lo stato del pin.
Returns
lo stato logico dell'ingresso: HIGH o LOW N.B. aggiorna currLevel.
Definition at line 181 of file ddigitalinput.cpp.
References currLevel, DRES_OK, handle, lastResult, pin, and readPin().
Referenced by begin(), isChanged(), isChangedToHigh(), isChangedToLow(), and main().
Member Data Documentation
currLevel
int DDigitalInput::currLevel private
Definition at line 25 of file ddigitalinput.h.
Referenced by begin(), DDigitalInput(), isChanged(), isChangedToHigh(), isChangedToLow(), and read().
currMsec
unsigned long DDigitalInput::currMsec private
Definition at line 27 of file ddigitalinput.h.
Referenced by isChanged(), isChangedToHigh(), and isChangedToLow().
debounceMsec
unsigned long DDigitalInput::debounceMsec private
Definition at line 29 of file ddigitalinput.h.
Referenced by begin(), isChanged(), isChangedToHigh(), and isChangedToLow().
handle
DGpioHandle DDigitalInput::handle private
Definition at line 31 of file ddigitalinput.h.
Referenced by begin(), DDigitalInput(), read(), and ~DDigitalInput().
lastResult
DResult DDigitalInput::lastResult private
Definition at line 32 of file ddigitalinput.h.
Referenced by begin(), DDigitalInput(), getLastError(), isAttached(), and read().
pin
int DDigitalInput::pin private
Definition at line 24 of file ddigitalinput.h.
Referenced by begin(), DDigitalInput(), getPin(), read(), and ~DDigitalInput().
prevLevel
int DDigitalInput::prevLevel private
Definition at line 26 of file ddigitalinput.h.
Referenced by begin(), DDigitalInput(), isChanged(), isChangedToHigh(), and isChangedToLow().
prevMsec
unsigned long DDigitalInput::prevMsec private
Definition at line 28 of file ddigitalinput.h.
Referenced by begin(), isChanged(), isChangedToHigh(), and isChangedToLow().
The documentation for this class was generated from the following files:
src/ddigitalinput/ddigitalinput.h
src/ddigitalinput/ddigitalinput.cpp