My Project: DI2CBus Class Reference
DI2CBus Class Reference
#include <di2cbus.h>
Classes
struct DI2CAdaper
Public Types
enum DScanMode { SCAN_MODE_READ , SCAN_MODE_WRITE }
Public Member Functions
DI2CBus (uint8_t busID)
~DI2CBus ()
int scanForDevices (DScanMode scanMode=SCAN_MODE_READ, uint8_t startAddr=0x08, uint8_t endAddr=0x77)
DI2CBusHandle handle (void)
bool isReady (void)
std::string getLastError (void)
std::string getInfo (void)
Static Public Member Functions
static int openI2CBus (int busID)
static int scanI2CBusses (std::vector< DI2CAdaper > &resultList)
Public Attributes
std::vector< uint8_t > devices
Private Attributes
std::string busName
uint8_t devAddr
DI2CBusHandle busHandle
std::string lastErrorString
Detailed Description
Definition at line 10 of file di2cbus.h.
Member Enumeration Documentation
DScanMode
enum DI2CBus::DScanMode
Enumerator
SCAN_MODE_READ
SCAN_MODE_WRITE
Definition at line 12 of file di2cbus.h.
Constructor & Destructor Documentation
DI2CBus()
DI2CBus::DI2CBus (uint8_t busID)
Definition at line 39 of file di2cbus.cpp.
References busHandle, busName, DI2C_BUS_DEV_PREFIX, and lastErrorString.
~DI2CBus()
DI2CBus::~DI2CBus ()
Definition at line 48 of file di2cbus.cpp.
References busHandle, and busName.
Member Function Documentation
getInfo()
std::string DI2CBus::getInfo (void)
Definition at line 104 of file di2cbus.cpp.
References busHandle, getLastError(), I2CFuncList, and lastErrorString.
Referenced by main().
getLastError()
std::string DI2CBus::getLastError (void)
Definition at line 99 of file di2cbus.cpp.
References lastErrorString.
Referenced by getInfo(), and main().
handle()
DI2CBusHandle DI2CBus::handle (void)
Definition at line 89 of file di2cbus.cpp.
References busHandle.
Referenced by main().
isReady()
bool DI2CBus::isReady (void)
Definition at line 94 of file di2cbus.cpp.
References busHandle.
openI2CBus()
int DI2CBus::openI2CBus (int busID) static
Definition at line 122 of file di2cbus.cpp.
References busHandle, busName, and DI2C_BUS_DEV_PREFIX.
Referenced by scanI2CBusses().
scanForDevices()
int DI2CBus::scanForDevices (DScanMode scanMode = SCAN_MODE_READ, uint8_t startAddr = 0x08, uint8_t endAddr = 0x77)
Definition at line 55 of file di2cbus.cpp.
References busHandle, devices, lastErrorString, SCAN_MODE_READ, and SCAN_MODE_WRITE.
Referenced by main().
scanI2CBusses()
int DI2CBus::scanI2CBusses (std::vector< DI2CAdaper > & resultList) static
Definition at line 138 of file di2cbus.cpp.
References ADAPTER_DUMMY, ADAPTER_I2C, ADAPTER_ISA, ADAPTER_SMBUS, ADAPTER_UNKNOWN, DI2CBus::DI2CAdaper::algo, busHandle, DI2CAdapterAlgo, DI2CAdapterFuncs, DI2CBus::DI2CAdaper::funcs, DI2CBus::DI2CAdaper::name, DI2CBus::DI2CAdaper::nr, and openI2CBus().
Referenced by main().
Member Data Documentation
busHandle
DI2CBusHandle DI2CBus::busHandle private
Definition at line 37 of file di2cbus.h.
Referenced by DI2CBus(), getInfo(), handle(), isReady(), openI2CBus(), scanForDevices(), scanI2CBusses(), and ~DI2CBus().
busName
std::string DI2CBus::busName private
Definition at line 35 of file di2cbus.h.
Referenced by DI2CBus(), openI2CBus(), and ~DI2CBus().
devAddr
uint8_t DI2CBus::devAddr private
Definition at line 36 of file di2cbus.h.
devices
std::vector<uint8_t> DI2CBus::devices
Definition at line 32 of file di2cbus.h.
Referenced by main(), and scanForDevices().
lastErrorString
std::string DI2CBus::lastErrorString private
Definition at line 38 of file di2cbus.h.
Referenced by DI2CBus(), getInfo(), getLastError(), and scanForDevices().
The documentation for this class was generated from the following files:
src/di2c/di2cbus.h
src/di2c/di2cbus.cpp