My Project: DStepper Class Reference
DStepper Class Reference
Library for handle Stepper Motor with a Power Module with Clock and Dir input.
#include <DStepper.h>
Public Types
enum DPinLevel { LOW_LEVEL , HIGH_LEVEL }
enum DPinMode { INPUT_MODE , OUTPUT_MODE , INPUT_PULLUP_MODE }
enum DRotationDir { ROT_CC , ROT_CW , ROT_CURRENT }
Public Member Functions
DStepper (uint8_t PinDir, uint8_t PinClk, uint16_t StepsPerRev=200)
TODO: _GetMaxRpm() _Step() _Optional Enable pin _Ramp StopPin _RampFreq.
~DStepper ()
Destroy the DStepper::DStepper object.
void begin ()
Initialize all needed stuffs to start lib (and do nothing else).
void begin (uint16_t FreqHz, bool Enabled)
Initialize all needed stuffs to start lib, set clock frequency and enable it on pin (if required).
void begin (uint8_t Rpm, bool Enabled)
Initialize all needed stuffs to start lib, set rpm value and enable it on pin (if required).
void SetSwappedDir (bool Enabled)
Invert level on PinDir when setting rotation direction.
void SetStepsPerRevolution (uint16_t Steps)
Set number of motor step for each revolution.
void SetClkDutyCycle (uint8_t DutyCyclePerc)
Set current pwm duty-cycle for clock pin.
uint16_t GetClkFreq (void)
Get current frequency on clock pin.
uint8_t GetClkDutyCycle (void)
Get current duty-cycle used for clock pin.
DStepper::DRotationDir GetDir (void)
Get current rotation direction.
uint16_t GetRpm (void)
Get current rpm value.
void On (void)
Enable pwm output, this starts the motor at CurrFreqHz and CurrDutyCycle values (output directly on pin).
void Off (void)
Disable pwm output, this stops the motor (output directly on pin).
void SetFreq (uint16_t FreqHz)
Set frequency to apply on clock pin.
void SetFreq (uint16_t FreqHz, uint8_t DutyCyclePerc)
Set frequency and duty-cycle to apply on clock pin.
void SetFreq (uint16_t FreqHz, DRotationDir RotationDir)
Set frequency to apply on clock pin and rotation direction.
void SetRpm (uint16_t Rpm)
Set speed (output directly on pin).
void SetRpm (uint16_t Rpm, DRotationDir RotationDir)
Set speed and direction (output directly on pin).
bool RampRpm (uint16_t RampMillis, uint16_t Rpm, DRotationDir RotationDir=ROT_CURRENT, int8_t FaultPin=-1, DPinLevel FaultLevel=LOW_LEVEL)
Reach Rpm speed using ramp (output directly on pin).
void SetDir (DRotationDir RotationDir)
Set direction (output directly on pin).
void SetDirCW (void)
Set rotation direction clockwise (output directly on pin).
void SetDirCC (void)
Set rotation direction counter-clockwise (output directly on pin).
void RevertDir (void)
Revert current rotation direction (output directly on pin).
Private Attributes
const uint8_t DirPin
const uint8_t ClkPin
DPwmOut * dPwmOut
uint16_t StepsPerRevol
uint8_t SwappedDir
uint16_t CurrFreqHz
uint8_t CurrDutyCycle
Detailed Description
Library for handle Stepper Motor with a Power Module with Clock and Dir input.
Definition at line 33 of file DStepper.h.
Member Enumeration Documentation
DPinLevel
enum DStepper::DPinLevel
Enumerator
LOW_LEVEL
HIGH_LEVEL
Definition at line 37 of file DStepper.h.
DPinMode
enum DStepper::DPinMode
Enumerator
INPUT_MODE
OUTPUT_MODE
INPUT_PULLUP_MODE
Definition at line 39 of file DStepper.h.
DRotationDir
enum DStepper::DRotationDir
Enumerator
ROT_CC
ROT_CW
ROT_CURRENT
Definition at line 41 of file DStepper.h.
Constructor & Destructor Documentation
DStepper()
DStepper::DStepper (uint8_t PinDir, uint8_t PinClk, uint16_t StepsPerRev = 200)
TODO: _GetMaxRpm() _Step() _Optional Enable pin _Ramp StopPin _RampFreq.
Create a StepperMotorDrv Object
Parameters
PinDir -> Digital Output Pin to set Direction of motor
PinClk -> Pwm Output Pin for Clock signal
StepsPerRev -> Number of motor step for each revolution. If your motor gives the number of degrees per step, divide that number into 360 to get the number of steps (e.g. 360 / 1.6 gives 200 steps). Default value 200 (1.6 degree per step).
Definition at line 47 of file DStepper.cpp.
References ClkPin, CurrDutyCycle, CurrFreqHz, DirPin, dPwmOut, OUTPUT_MODE, ROT_CW, SetDir(), StepsPerRevol, and SwappedDir.
~DStepper()
DStepper::~DStepper ()
Destroy the DStepper::DStepper object.
Definition at line 67 of file DStepper.cpp.
References dPwmOut.
Member Function Documentation
begin() [1/3]
void DStepper::begin (void)
Initialize all needed stuffs to start lib (and do nothing else).
Initialize DSoftPwm lib used to generate pwm signal. The pwm signal use mcu timer and ISR (interrupt service routine), but ISR cannot be initialized inside constructors (make some strange things timing mistakes), so, must be call after contructor to make DStepper lib to work.
Definition at line 78 of file DStepper.cpp.
References DPwmOut::begin(), and dPwmOut.
begin() [2/3]
void DStepper::begin (uint16_t FreqHz, bool Enabled)
Initialize all needed stuffs to start lib, set clock frequency and enable it on pin (if required).
Initialize DSoftPwm lib used to generate pwm signal. The pwm signal use mcu timer and ISR (interrupt service routine), but ISR cannot be initialized inside constructors (make some strange things timing mistakes), so, must be call after contructor to make DStepper lib to work.
Parameters
FreqHz -> Frequency in Hz.
Enabled -> If true, pwm is enable on clock pin.
Definition at line 92 of file DStepper.cpp.
References DPwmOut::begin(), dPwmOut, and SetFreq().
begin() [3/3]
void DStepper::begin (uint8_t Rpm, bool Enabled)
Initialize all needed stuffs to start lib, set rpm value and enable it on pin (if required).
Initialize DSoftPwm lib used to generate pwm signal. The pwm signal use mcu timer and ISR (interrupt service routine), but ISR cannot be initialized inside constructors (make some strange things timing mistakes), so, must be call after contructor to make DStepper lib to work.
Parameters
Rpm -> Rpm value used to calulate clock frequency.
Enabled -> If true, pwm is enable on clock pin.
Definition at line 110 of file DStepper.cpp.
References DPwmOut::begin(), dPwmOut, and SetRpm().
GetClkDutyCycle()
uint8_t DStepper::GetClkDutyCycle (void)
Get current duty-cycle used for clock pin.
Returns
uint8_t -> Duty-cycle value in percentual.
Definition at line 180 of file DStepper.cpp.
References CurrDutyCycle.
GetClkFreq()
uint16_t DStepper::GetClkFreq (void)
Get current frequency on clock pin.
Returns
uint16_t Frequency in Hz.
Definition at line 170 of file DStepper.cpp.
References CurrFreqHz.
GetDir()
DStepper::DRotationDir DStepper::GetDir (void)
Get current rotation direction.
Returns
ROT_CW for clocwWise direction, ROT_CC for counter-clockwise direction.
Definition at line 189 of file DStepper.cpp.
References DirPin, and SwappedDir.
GetRpm()
uint16_t DStepper::GetRpm (void)
Get current rpm value.
Returns
uint16_t rpm value.
Definition at line 199 of file DStepper.cpp.
References CurrFreqHz, and StepsPerRevol.
Referenced by RampRpm().
Off()
void DStepper::Off (void)
Disable pwm output, this stops the motor (output directly on pin).
Definition at line 219 of file DStepper.cpp.
References dPwmOut.
On()
void DStepper::On (void)
Enable pwm output, this starts the motor at CurrFreqHz and CurrDutyCycle values (output directly on pin).
Definition at line 211 of file DStepper.cpp.
References dPwmOut.
RampRpm()
bool DStepper::RampRpm (uint16_t RampMillis, uint16_t Rpm, DRotationDir RotationDir = ROT_CURRENT, int8_t FaultPin = -1, DPinLevel FaultLevel = LOW_LEVEL)
Reach Rpm speed using ramp (output directly on pin).
Change speed from CurrRpm to Rpm in time of RampMillis. N.B.: -Ramp is calculated for both increase and decrese speed. -Motor rotation direction still remain to this RotationDir value. -One pin is used as emergency stop.
e.g.
{.C++}
// If Pin 2 wil trigger a LOW_LEVEL status funcion stops before Ramp time.
bool fault=Ramp(120,4000,CC,2,LOW_LEVEL); // Reach 120 rpm in 4 seconds
if (!fault) {
    Ramp(60,2000,CC,2,LOW_LEVEL); // Decrease to 60 rpm in 2 seconds
}
if (!fault) {
    Ramp(0,2000,CC,2,LOW_LEVEL); // Stop motor in 2 seconds
}
Parameters
RampMillis -> Duration of ramp in milliseconds. Setting a value if 0, immedialtly apply Rpm value.
Rpm -> Rpm value to set.
RotationDir -> Specify rotation direction ROT_CC or ROT_CW. ROT_CURRENT will not change it.
FaultPin -> Pin used to emergency stop motor, when this pin is in FaultLevel, motor will be stopped. A value of -1 disable the check (!! BE CAREFULLY !!).
FaultLevel -> The FaultPin level that triggers the emergency stop.
Returns
false if FaultPin has triggered an emergency stop, otherwise, after RampMillis time, return true.
Definition at line 315 of file DStepper.cpp.
References CurrDutyCycle, dPwmOut, GetRpm(), millis(), ROT_CURRENT, SetDir(), SetRpm(), and StepsPerRevol.
RevertDir()
void DStepper::RevertDir (void)
Revert current rotation direction (output directly on pin).
Definition at line 380 of file DStepper.cpp.
References DirPin.
SetClkDutyCycle()
void DStepper::SetClkDutyCycle (uint8_t DutyCyclePerc)
Set current pwm duty-cycle for clock pin.
Parameters
DutyCyclePerc -> Duty-cycle value in percentual from 0 to 100. Value of 0 put pin always LOW. Value of 100 put clck pin always HIGH.
Definition at line 156 of file DStepper.cpp.
References CurrDutyCycle.
SetDir()
void DStepper::SetDir (DRotationDir RotationDir)
Set direction (output directly on pin).
Parameters
RotationDir -> ROT_CW for clocwWise direction, ROT_CC for counter-clockwise direction.
N.B. Real rotation direction depends from motor board hardware, if your direction does not match, use EnableDirSwapMode(true) to correct it.
Definition at line 356 of file DStepper.cpp.
References DirPin, and SwappedDir.
Referenced by DStepper(), RampRpm(), SetDirCC(), SetDirCW(), SetFreq(), and SetRpm().
SetDirCC()
void DStepper::SetDirCC (void)
Set rotation direction counter-clockwise (output directly on pin).
Definition at line 372 of file DStepper.cpp.
References ROT_CC, and SetDir().
SetDirCW()
void DStepper::SetDirCW (void)
Set rotation direction clockwise (output directly on pin).
Definition at line 364 of file DStepper.cpp.
References ROT_CW, and SetDir().
SetFreq() [1/3]
void DStepper::SetFreq (uint16_t FreqHz)
Set frequency to apply on clock pin.
Parameters
FreqHz -> Frequency in Hz to out on clocl pin.
Definition at line 254 of file DStepper.cpp.
References CurrDutyCycle, CurrFreqHz, and dPwmOut.
Referenced by begin().
SetFreq() [2/3]
void DStepper::SetFreq (uint16_t FreqHz, DRotationDir RotationDir)
Set frequency to apply on clock pin and rotation direction.
Parameters
FreqHz -> Frequency in Hz to out on clocl pin.
RotationDir -> ROT_CC for counter clockwise or ROT_CW for clockwise.
Definition at line 266 of file DStepper.cpp.
References CurrDutyCycle, CurrFreqHz, dPwmOut, and SetDir().
SetFreq() [3/3]
void DStepper::SetFreq (uint16_t FreqHz, uint8_t DutyCyclePerc)
Set frequency and duty-cycle to apply on clock pin.
Parameters
FreqHz -> Frequency in Hz to out on clocl pin.
DutyCyclePerc -> CC for counter clockwise or CW for clockwise.
Definition at line 279 of file DStepper.cpp.
References CurrDutyCycle, CurrFreqHz, and dPwmOut.
SetRpm() [1/2]
void DStepper::SetRpm (uint16_t Rpm)
Set speed (output directly on pin).
Parameters
Rpm -> Rpm value to set.
Definition at line 229 of file DStepper.cpp.
References CurrDutyCycle, CurrFreqHz, dPwmOut, and StepsPerRevol.
Referenced by begin(), and RampRpm().
SetRpm() [2/2]
void DStepper::SetRpm (uint16_t Rpm, DStepper::DRotationDir RotationDir)
Set speed and direction (output directly on pin).
Parameters
Rpm -> Rpm value to set.
RotationDir -> ROT_CC for counter clockwise or ROT_CW for clockwise. N.B. RotationDir will be inverted if SwapDirection is set to 1.
Definition at line 242 of file DStepper.cpp.
References CurrDutyCycle, CurrFreqHz, dPwmOut, SetDir(), and StepsPerRevol.
SetStepsPerRevolution()
void DStepper::SetStepsPerRevolution (uint16_t Steps)
Set number of motor step for each revolution.
If your motor gives the number of degrees per step, divide that number into 360 to get the number of steps (e.g. 360 / 1.6 gives 200 steps).
Parameters
Steps the number of steps in one revolution of your motor.
Definition at line 144 of file DStepper.cpp.
References StepsPerRevol.
SetSwappedDir()
void DStepper::SetSwappedDir (bool Enabled)
Invert level on PinDir when setting rotation direction.
Parameters
Enabled -> if true, direction handle is inverted.
Definition at line 128 of file DStepper.cpp.
References SwappedDir.
Member Data Documentation
ClkPin
const uint8_t DStepper::ClkPin private
Definition at line 85 of file DStepper.h.
Referenced by DStepper().
CurrDutyCycle
uint8_t DStepper::CurrDutyCycle private
Definition at line 90 of file DStepper.h.
Referenced by DStepper(), GetClkDutyCycle(), RampRpm(), SetClkDutyCycle(), SetFreq(), and SetRpm().
CurrFreqHz
uint16_t DStepper::CurrFreqHz private
Definition at line 89 of file DStepper.h.
Referenced by DStepper(), GetClkFreq(), GetRpm(), SetFreq(), and SetRpm().
DirPin
const uint8_t DStepper::DirPin private
Definition at line 84 of file DStepper.h.
Referenced by DStepper(), GetDir(), RevertDir(), and SetDir().
dPwmOut
DPwmOut* DStepper::dPwmOut private
Definition at line 86 of file DStepper.h.
Referenced by begin(), DStepper(), Off(), On(), RampRpm(), SetFreq(), SetRpm(), and ~DStepper().
StepsPerRevol
uint16_t DStepper::StepsPerRevol private
Definition at line 87 of file DStepper.h.
Referenced by DStepper(), GetRpm(), RampRpm(), SetRpm(), and SetStepsPerRevolution().
SwappedDir
uint8_t DStepper::SwappedDir private
Definition at line 88 of file DStepper.h.
Referenced by DStepper(), GetDir(), SetDir(), and SetSwappedDir().
The documentation for this class was generated from the following files:
src/_dstepper/DStepper.h
src/_dstepper/DStepper.cpp