My Project: DMenu Class Reference
DMenu Class Reference
#include <DMenu.h>
Public Types
enum DMenuAction { DMENU_ACTION_SELECT , DMENU_ACTION_UP , DMENU_ACTION_DOWN , DMENU_ACTION_BACK }
typedef void(* DMenuListener) (DMenu *MenuItem, BYTE Action)
typedef void(* DMenuListener) (DMenu *MenuItem, DMenuAction Action)
Public Member Functions
DMenu (const char MenuItemName[], DMenuListener CallbackFunc=NULL, DMenu *Parent=NULL)
Contructor.
~DMenu ()
Destructor.
void Init (const char MenuItemName[], DMenuListener CallbackFunc, DMenu *ParentItem)
Initialize all stuffs from constructors.
void SetName (const char ItemName[])
Set the name of Item.
short int AddItem (const char Name[], bool SetCurrent=false)
Add a new Item to menu.
DMenu * Up (void)
Change current selected Item to previous one.
DMenu * Down (void)
Change current selected Item to next one.
DMenu * Back (void)
If this have a Parent Item, Calling Back() will also fire a Callback event passing the Parent Item as argument, otherwise return NULL.
DMenu * Select (void)
Fire a Callback event sending the current selected Item as argument.
DMenu * GetItem (short int Index)
Add a list of Items.
DMenu * GetCurrItem (void)
DMenu * GetParent (void)
N.B.
short int GetItemsCount (void)
const char * GetName (void)
short int GetID (void)
short int GetCurrItemIndex (void)
if -1 is returned, no item is selected
DMenu (const char MenuItemName[], int MenuID=-1, DMenu *Parent=NULL, DMenuListener CallbackFunc=NULL)
Construct a new DMenu::DMenu object.
~DMenu ()
void Init (const char MenuItemName[], int MenuID, DMenu *ParentItem, DMenuListener CallbackFunc)
void SetName (const char ItemName[])
bool AddItem (const char Name[])
bool AddItem (const char Name[], int ItemID)
bool AddItem (const char ItemName[], bool SetCurrent)
bool AddItem (const char Name[], int ItemID, bool SetCurrent)
Add new menu item.
DMenu * Up (void)
DMenu * Down (void)
DMenu * Back (void)
DMenu * Select (void)
DMenu * GetItem (short int Index)
DMenu * GetCurrItem (void)
DMenu * GetParent (void)
bool HasParent (void)
uint8_t GetItemsCount (void)
const char * GetName (void)
bool NameEquals (const char MenuName[])
uint8_t GetID (void)
short int GetCurrItemIndex (void)
Public Attributes
bool Loop
Private Attributes
DMenuListener Callback
char * Name
DMenu * Parent
short int ItemIndex
short int ItemsCount
Index used to handle the current selected Item.
short int ID
BYTE MaxItemTextLen
DMenu ** Items
uint8_t ItemsCount
Index used to handle the current selected Item.
int ID
uint8_t MaxItemTextLen
Detailed Description
Definition at line 38 of file DMenu.h.
Member Typedef Documentation
DMenuListener [1/2]
typedef void(* DMenu::DMenuListener) (DMenu *MenuItem, BYTE Action)
Definition at line 40 of file DMenu.h.
DMenuListener [2/2]
typedef void(* DMenu::DMenuListener) (DMenu *MenuItem, DMenuAction Action)
Definition at line 30 of file DMenu.h.
Member Enumeration Documentation
DMenuAction
enum DMenu::DMenuAction
Enumerator
DMENU_ACTION_SELECT
DMENU_ACTION_UP
DMENU_ACTION_DOWN
DMENU_ACTION_BACK
Definition at line 28 of file DMenu.h.
Constructor & Destructor Documentation
DMenu() [1/2]
DMenu::DMenu (const char MenuItemName[], DMenuListener CallbackFunc = NULL, DMenu * ParentItem = NULL)
Contructor.
Parameters
MenuItemName -> name of new Menu Item
CallbackFunc -> pointer to the DMenuListener function that will be called on Select() or Back() call
ParentItem -> pointer to the parent Item of the new one. If parameter is NULL the Menu Item is the root one and Back() does't fire the Callback
Definition at line 9 of file DMenu.cpp.
References Init().
Referenced by AddItem().
~DMenu() [1/2]
DMenu::~DMenu ()
Destructor.
Definition at line 34 of file DMenu.cpp.
References Items, and ItemsCount.
DMenu() [2/2]
DMenu::DMenu (const char MenuItemName[], int MenuID = -1, DMenu * ParentItem = NULL, DMenuListener CallbackFunc = NULL) explicit
Construct a new DMenu::DMenu object.
Parameters
MenuItemName -> name of new menu item.
MenuID -> ID of this menu. You can use it to handle it by id instead of by name. Can be a value from 0 to 254.
ParentItem -> pointer to the parent item of the new one. If parameter is NULL the menu item is the root one and Back() does't fire the Callback.
CallbackFunc -> pointer to the DMenuListener function that will be called on Select() or Back() call.
Definition at line 14 of file DMenu.cpp.
References Init().
~DMenu() [2/2]
DMenu::~DMenu ()
Member Function Documentation
AddItem() [1/5]
bool DMenu::AddItem (const char ItemName[], bool SetCurrent)
AddItem() [2/5]
bool DMenu::AddItem (const char Name[])
Definition at line 89 of file DMenu.cpp.
References AddItem().
AddItem() [3/5]
bool DMenu::AddItem (const char ItemName[], bool SetCurrent = false)
Add a new Item to menu.
The item is added to the end
Parameters
ItemName -> Name of Item
SetCurrent -> if true set new Item as current one
Returns
ID of the created item or 0 if any error occours
Definition at line 71 of file DMenu.cpp.
References Callback, DMenu(), GetID(), ItemIndex, Items, and ItemsCount.
Referenced by AddItem(), CreateMainMenu(), CreateSubMenu1(), CreateSubMenu2(), MenuDCMotorSetup(), MenuDCMotorSetupPin(), MenuMain(), MenuMotor(), and MenuServoSetup().
AddItem() [4/5]
bool DMenu::AddItem (const char Name[], int ItemID)
Definition at line 94 of file DMenu.cpp.
References AddItem().
AddItem() [5/5]
bool DMenu::AddItem (const char ItemName[], int ItemID, bool SetCurrent)
Add new menu item.
Parameters
ItemName -> Name of Item.
MenuID -> ID of new sub menu. You can use it to handle it by id instead of by name. Can be a value from 0 to 254.
SetCurrent -> if true set new Item as current one.
Returns
true of the created item or false if any error occours.
Definition at line 113 of file DMenu.cpp.
References Callback, DMenu(), ItemIndex, Items, and ItemsCount.
Back() [1/2]
DMenu * DMenu::Back (void)
If this have a Parent Item, Calling Back() will also fire a Callback event passing the Parent Item as argument, otherwise return NULL.
Returns
the Parent Item of this
Definition at line 222 of file DMenu.cpp.
References Callback, DMENU_ACTION_BACK, and Parent.
Back() [2/2]
DMenu* DMenu::Back (void)
Down() [1/2]
DMenu * DMenu::Down (void)
Change current selected Item to next one.
Returns
-> a pointer to new current selected Item
Definition at line 193 of file DMenu.cpp.
References Callback, DMENU_ACTION_DOWN, ItemIndex, Items, ItemsCount, and Loop.
Referenced by loop().
Down() [2/2]
DMenu* DMenu::Down (void)
GetCurrItem() [1/2]
DMenu * DMenu::GetCurrItem (void)
Returns
current selected Item inside this Menu
Definition at line 137 of file DMenu.cpp.
References ItemIndex, and Items.
GetCurrItem() [2/2]
DMenu* DMenu::GetCurrItem (void)
GetCurrItemIndex() [1/2]
short int DMenu::GetCurrItemIndex (void)
if -1 is returned, no item is selected
Returns
zero based index of current selected item
Definition at line 264 of file DMenu.cpp.
References ItemIndex.
Referenced by PrintMenu().
GetCurrItemIndex() [2/2]
short int DMenu::GetCurrItemIndex (void)
GetID() [1/2]
uint8_t DMenu::GetID (void)
Returns
ID of this Item
Definition at line 254 of file DMenu.cpp.
References ID.
Referenced by AddItem(), loop(), and PrintMenu().
GetID() [2/2]
uint8_t DMenu::GetID (void)
GetItem() [1/2]
DMenu * DMenu::GetItem (short int Index)
Add a list of Items.
The items are added to the end
Parameters
Names -> a vector of string containing the name of items to create
Returns
a pointer to new Item
Item at Index position
Item at Index position
Definition at line 127 of file DMenu.cpp.
References Items, and ItemsCount.
Referenced by PrintMenu().
GetItem() [2/2]
DMenu* DMenu::GetItem (short int Index)
GetItemsCount() [1/2]
uint8_t DMenu::GetItemsCount (void)
Returns
numbers of DMenu Items in this Menu
Definition at line 155 of file DMenu.cpp.
References ItemsCount.
Referenced by PrintMenu().
GetItemsCount() [2/2]
uint8_t DMenu::GetItemsCount (void)
GetName() [1/2]
const char * DMenu::GetName (void)
Returns
name string of this Item
Definition at line 248 of file DMenu.cpp.
References Name.
Referenced by loop(), and PrintMenu().
GetName() [2/2]
const char* DMenu::GetName (void)
GetParent() [1/2]
DMenu * DMenu::GetParent (void)
N.B.
Returns
parent Item If this menu has no Parent the function return this
Definition at line 149 of file DMenu.cpp.
References Parent.
GetParent() [2/2]
DMenu* DMenu::GetParent (void)
HasParent()
bool DMenu::HasParent (void)
Definition at line 180 of file DMenu.cpp.
References Parent.
Init() [1/2]
void DMenu::Init (const char MenuItemName[], DMenuListener CallbackFunc, DMenu * ParentItem)
Initialize all stuffs from constructors.
Definition at line 15 of file DMenu.cpp.
References Callback, DMENU_DEFAULT_MAX_ITEM_TEXT_LEN, DMENU_MAX_ITEMS, ID, ItemIndex, ItemsCount, Loop, MaxItemTextLen, Name, Parent, and SetName().
Referenced by DMenu().
Init() [2/2]
void DMenu::Init (const char MenuItemName[], int MenuID, DMenu * ParentItem, DMenuListener CallbackFunc)
Parameters
MenuItemName -> name of new menu item.
MenuID -> ID of this menu. You can use it to handle it by id instead of by name. Can be a value from 0 to 254. A value of -1 means "no id set".
ParentItem -> pointer to the parent item of the new one. If parameter is NULL the menu item is the root one and Back() does't fire the Callback.
CallbackFunc -> pointer to the DMenuListener function that will be called on Select() or Back() call.
Definition at line 28 of file DMenu.cpp.
References Callback, DMENU_DEFAULT_MAX_ITEM_TEXT_LEN, ID, ItemIndex, Items, ItemsCount, Loop, MaxItemTextLen, Name, Parent, and SetName().
NameEquals()
bool DMenu::NameEquals (const char MenuName[])
Definition at line 284 of file DMenu.cpp.
References Name.
Select() [1/2]
DMenu * DMenu::Select (void)
Fire a Callback event sending the current selected Item as argument.
N.B. Callback will be called only if there is a selected Item.
Definition at line 234 of file DMenu.cpp.
References Callback, DMENU_ACTION_SELECT, ItemIndex, and Items.
Referenced by loop().
Select() [2/2]
DMenu* DMenu::Select (void)
SetName() [1/2]
void DMenu::SetName (const char ItemName[])
Set the name of Item.
Parameters
new name of this Item.
N.B. The Name will be truncated to MaxItenTextLen value
Definition at line 51 of file DMenu.cpp.
References MaxItemTextLen, and Name.
Referenced by Init().
SetName() [2/2]
void DMenu::SetName (const char ItemName[])
Up() [1/2]
DMenu * DMenu::Up (void)
Change current selected Item to previous one.
Returns
-> a pointer to new current selected Item
Definition at line 164 of file DMenu.cpp.
References Callback, DMENU_ACTION_UP, ItemIndex, Items, ItemsCount, and Loop.
Up() [2/2]
DMenu* DMenu::Up (void)
Member Data Documentation
Callback
DMenuListener DMenu::Callback private
Definition at line 61 of file DMenu.h.
Referenced by AddItem(), Back(), Down(), Init(), Select(), and Up().
ID [1/2]
short int DMenu::ID private
Definition at line 66 of file DMenu.h.
Referenced by GetID(), and Init().
ID [2/2]
int DMenu::ID private
Definition at line 61 of file DMenu.h.
ItemIndex
short int DMenu::ItemIndex private
Definition at line 64 of file DMenu.h.
Referenced by AddItem(), Down(), GetCurrItem(), GetCurrItemIndex(), Init(), Select(), and Up().
Items
DMenu ** DMenu::Items private
Definition at line 68 of file DMenu.h.
Referenced by AddItem(), Down(), GetCurrItem(), GetItem(), Init(), Select(), Up(), and ~DMenu().
ItemsCount [1/2]
short int DMenu::ItemsCount private
Index used to handle the current selected Item.
Definition at line 65 of file DMenu.h.
Referenced by AddItem(), Down(), GetItem(), GetItemsCount(), Init(), Up(), and ~DMenu().
ItemsCount [2/2]
uint8_t DMenu::ItemsCount private
Index used to handle the current selected Item.
Definition at line 60 of file DMenu.h.
Loop
bool DMenu::Loop
Definition at line 58 of file DMenu.h.
Referenced by CreateMainMenu(), CreateSubMenu1(), CreateSubMenu2(), Down(), Init(), MenuDCMotorSetup(), MenuDCMotorSetupPin(), MenuMain(), MenuMotor(), MenuServoSetup(), and Up().
MaxItemTextLen [1/2]
BYTE DMenu::MaxItemTextLen private
Definition at line 67 of file DMenu.h.
Referenced by Init(), and SetName().
MaxItemTextLen [2/2]
uint8_t DMenu::MaxItemTextLen private
Definition at line 62 of file DMenu.h.
Name
char * DMenu::Name private
Definition at line 62 of file DMenu.h.
Referenced by GetName(), Init(), NameEquals(), and SetName().
Parent
DMenu * DMenu::Parent private
Definition at line 63 of file DMenu.h.
Referenced by Back(), GetParent(), HasParent(), and Init().
The documentation for this class was generated from the following files:
examples/_ddigitalbutton/arduino-ide-ddigitalbutton-demo/DMenu.h
examples/_ddigitalbutton/arduino-ide-ddigitalbutton-demo/DMenu.cpp