My Project: DPwmOut Class Reference
DPwmOut Class Reference
#include <dpwm.h>
Public Member Functions
DPwmOut (uint8_t GpioPin)
~DPwmOut ()
Destroy the DPwmOut::DPwmOut object and free pin use.
void release (void)
bool begin (uint16_t FreqHz=0, uint8_t DutyCyclePerc=50, bool Activate=false)
void set (uint16_t FreqHz, uint8_t DutyCyclePerc, bool Activate)
void setHz (uint16_t FreqHz)
void setDutyPerc (uint8_t DutyCyclePerc)
void setMicros (uint16_t Us)
Set duration of pwm pulse in microseconds.
void on (bool PwmOn=true)
void high (void)
Set still HIGH value on pin.
void low (void)
Set still LOW value on pin.
void printInfo (void)
bool isReady (void)
bool isActive (void)
uint16_t getPeriodUs (void)
uint8_t getPin (void)
uint8_t getDutyPerc (void)
void printInterruptLoad ()
DPwmOut (int gpioPin, DGpioHandle gpioHandle=-1)
Construct a new DPwmOut::DPwmOut object.
~DPwmOut ()
void release (void)
bool begin (float frequecyHz=0.0, float dutyCyclePerc=50.0, bool activate=false)
Init all stuff for starting pwm on GpioPin.
bool set (float frequecyHz, float dutyCyclePerc, bool activate)
Set pwm frequency and duty-cycle.
bool setHz (float frequecyHz)
Set the frequency of pwm and activate pwm.
bool setDutyPerc (float dutyCyclePerc)
Set the pwm duty-cycle and activate pwm.
bool setMicros (uint16_t us)
bool on (bool pwmOn=true)
bool high (void)
bool low (void)
bool isReady (void)
bool isActive (void)
uint16_t getPeriodUs (void)
uint8_t getPin (void)
uint8_t getDutyPerc (void)
std::string getLastError (void)
Public Attributes
uint8_t Pin
uint8_t BitMask =0
volatile uint8_t * OUTPORT
bool Active =false
uint32_t TickCounter =0
Pwm active (default off).
uint32_t TicksON =0
ISR call counter.
uint32_t TicksTOT =0
Number of ticks for HIGH time.
uint8_t dutyPerc
Numebr of ticks of total period.
int pin
bool active
float freqHz
Pwm active (default off).
float dutyPerc
DGpioHandle handle
DResult lastResult
Detailed Description
Definition at line 4 of file dpwm.h.
Constructor & Destructor Documentation
DPwmOut() [1/2]
DPwmOut::DPwmOut (uint8_t GpioPin)
~DPwmOut() [1/2]
DPwmOut::~DPwmOut ()
Destroy the DPwmOut::DPwmOut object and free pin use.
Definition at line 35 of file dpwm.cpp.
References handle, pin, and releasePin().
DPwmOut() [2/2]
DPwmOut::DPwmOut (int gpioPin, DGpioHandle gpioHandle = -1)
Construct a new DPwmOut::DPwmOut object.
N.B. Timer should have not been initialized in costructor (may be it doe not work). Timer will be initialized in Begin().
Definition at line 10 of file dpwm.cpp.
References DERR_CLASS_NOT_BEGUN, DERR_GPIO_NOT_READY, handle, initGpio(), isGpioReady(), lastResult, and pin.
~DPwmOut() [2/2]
DPwmOut::~DPwmOut ()
Member Function Documentation
begin() [1/2]
bool DPwmOut::begin (float frequecyHz = 0.0, float dutyCyclePerc = 50.0, bool activate = false)
Init all stuff for starting pwm on GpioPin.
MUST be calld before using the class.
Parameters
GpioPin
FreqHz
DutyCyclePerc
Activate
Definition at line 49 of file dpwm.cpp.
References active, DRES_OK, dutyPerc, freqHz, handle, initPin(), lastResult, NO_FLAGS, pin, set(), and SOFT_PWM.
begin() [2/2]
bool DPwmOut::begin (uint16_t FreqHz = 0, uint8_t DutyCyclePerc = 50, bool Activate = false)
Referenced by DDCMotor::attach(), DStepper::begin(), DServo::begin(), and main().
getDutyPerc() [1/2]
uint8_t DPwmOut::getDutyPerc (void)
Definition at line 219 of file dpwm.cpp.
References dutyPerc.
getDutyPerc() [2/2]
uint8_t DPwmOut::getDutyPerc (void)
getLastError()
std::string DPwmOut::getLastError (void)
Definition at line 223 of file dpwm.cpp.
References getErrorCode(), and lastResult.
Referenced by DServo::getLastError(), and main().
getPeriodUs() [1/2]
uint16_t DPwmOut::getPeriodUs (void)
Returns
uint16_t the period of pwm pulse.
Definition at line 205 of file dpwm.cpp.
References freqHz.
Referenced by DDCMotor::attach(), and setMicros().
getPeriodUs() [2/2]
uint16_t DPwmOut::getPeriodUs (void)
getPin() [1/2]
uint8_t DPwmOut::getPin (void)
Returns
uint8_t pwm pin number.
Definition at line 214 of file dpwm.cpp.
References pin.
Referenced by DServo::getPin(), DDCMotor::GetPinDirPwm(), and DDCMotor::GetPinPwm().
getPin() [2/2]
uint8_t DPwmOut::getPin (void)
high() [1/2]
bool DPwmOut::high (void)
Set still HIGH value on pin.
Definition at line 171 of file dpwm.cpp.
References DRES_OK, handle, HIGH, lastResult, pin, and writePin().
Referenced by DDCMotor::SetVel().
high() [2/2]
bool DPwmOut::high (void)
isActive() [1/2]
bool DPwmOut::isActive (void)
Returns
true if on Pin is present a pwm signal.
false if Pin is in HIGH or LOW state.
Definition at line 198 of file dpwm.cpp.
References active.
isActive() [2/2]
bool DPwmOut::isActive (void)
isReady() [1/2]
bool DPwmOut::isReady (void)
Returns
true if Pwm for this pin is ready to use. N.B. Does not return the output enable status (use IsEnabled() instead).
Definition at line 189 of file dpwm.cpp.
References DRES_OK, and lastResult.
Referenced by DDCMotor::attached(), and DServo::attached().
isReady() [2/2]
bool DPwmOut::isReady (void)
low() [1/2]
bool DPwmOut::low (void)
Set still LOW value on pin.
Definition at line 180 of file dpwm.cpp.
References DRES_OK, handle, lastResult, LOW, pin, and writePin().
Referenced by DDCMotor::Brake(), and DDCMotor::SetVel().
low() [2/2]
bool DPwmOut::low (void)
on() [1/2]
bool DPwmOut::on (bool PwmOn = true)
Definition at line 156 of file dpwm.cpp.
References DRES_OK, freqHz, handle, lastResult, pin, and set().
Referenced by DServo::begin().
on() [2/2]
bool DPwmOut::on (bool pwmOn = true)
printInfo()
void DPwmOut::printInfo (void)
printInterruptLoad()
void DPwmOut::printInterruptLoad ()
release() [1/2]
void DPwmOut::release (void)
Referenced by DDCMotor::detach().
release() [2/2]
void DPwmOut::release (void)
set() [1/2]
bool DPwmOut::set (float frequecyHz, float dutyCyclePerc, bool activate)
Set pwm frequency and duty-cycle.
Parameters
freqHz frequency in Hz (0=off, 0.1-10000).
dutyCyclePerc PWM duty cycle in % (0-100).
activate if true, pwm pulse will be out.
Definition at line 69 of file dpwm.cpp.
References active, dutyPerc, freqHz, handle, lastResult, MAX_PWM_FREQ, and pin.
set() [2/2]
void DPwmOut::set (uint16_t FreqHz, uint8_t DutyCyclePerc, bool Activate)
Referenced by begin(), main(), on(), setDutyPerc(), and setHz().
setDutyPerc() [1/2]
bool DPwmOut::setDutyPerc (float dutyCyclePerc)
Set the pwm duty-cycle and activate pwm.
Parameters
DutyCyclePerc -> duty-cycle value in percentual (from 0 to 100): 1 to 99 : generate pwm signal. 0 : pin is put in LOW level. >=100 : pin is put in HIGH level.
Definition at line 118 of file dpwm.cpp.
References freqHz, and set().
setDutyPerc() [2/2]
void DPwmOut::setDutyPerc (uint8_t DutyCyclePerc)
setHz() [1/2]
bool DPwmOut::setHz (float frequecyHz)
Set the frequency of pwm and activate pwm.
Parameters
FreqHz frequency in Hz (0=off, 0.1-10000)
Definition at line 106 of file dpwm.cpp.
References dutyPerc, freqHz, and set().
setHz() [2/2]
void DPwmOut::setHz (uint16_t FreqHz)
setMicros() [1/2]
bool DPwmOut::setMicros (uint16_t us)
Set duration of pwm pulse in microseconds.
If pulse is greater than current period, duty cycle wil be set 100%. The frequency is 1000000 / (pulseOn us + pulseOff us) Hz, so: pulseOff us = (1000000 / frequency hz) - pulseOn us
The set duty cycle will be pulseOn / (pulseOn + pulseOff) * 100 %
Parameters
us
Definition at line 133 of file dpwm.cpp.
References DRES_OK, dutyPerc, freqHz, getPeriodUs(), handle, lastResult, and pin.
Referenced by DServo::begin(), DDCMotor::Brake(), DServo::servoOut(), and DDCMotor::SetVel().
setMicros() [2/2]
bool DPwmOut::setMicros (uint16_t us)
Member Data Documentation
Active
bool DPwmOut::Active =false
Definition at line 29 of file dpwm.h.
active
bool DPwmOut::active
Definition at line 28 of file dpwm.h.
Referenced by begin(), isActive(), and set().
BitMask
uint8_t DPwmOut::BitMask =0
Definition at line 27 of file dpwm.h.
dutyPerc [1/2]
uint8_t DPwmOut::dutyPerc
Numebr of ticks of total period.
Definition at line 33 of file dpwm.h.
Referenced by begin(), getDutyPerc(), set(), setHz(), and setMicros().
dutyPerc [2/2]
float DPwmOut::dutyPerc
Definition at line 30 of file dpwm.h.
freqHz
float DPwmOut::freqHz
Pwm active (default off).
Definition at line 29 of file dpwm.h.
Referenced by begin(), getPeriodUs(), on(), set(), setDutyPerc(), setHz(), and setMicros().
handle
DGpioHandle DPwmOut::handle
Definition at line 32 of file dpwm.h.
Referenced by begin(), DPwmOut(), high(), low(), on(), set(), setMicros(), and ~DPwmOut().
lastResult
DResult DPwmOut::lastResult
Definition at line 33 of file dpwm.h.
Referenced by begin(), DPwmOut(), getLastError(), high(), isReady(), low(), on(), set(), and setMicros().
OUTPORT
volatile uint8_t* DPwmOut::OUTPORT
Definition at line 28 of file dpwm.h.
Pin
uint8_t DPwmOut::Pin
Definition at line 26 of file dpwm.h.
pin
int DPwmOut::pin
Definition at line 27 of file dpwm.h.
Referenced by begin(), DPwmOut(), getPin(), high(), low(), on(), set(), setMicros(), and ~DPwmOut().
TickCounter
uint32_t DPwmOut::TickCounter =0
Pwm active (default off).
Definition at line 30 of file dpwm.h.
TicksON
uint32_t DPwmOut::TicksON =0
ISR call counter.
Definition at line 31 of file dpwm.h.
TicksTOT
uint32_t DPwmOut::TicksTOT =0
Number of ticks for HIGH time.
Definition at line 32 of file dpwm.h.
The documentation for this class was generated from the following files:
src/dpwm/avr/dpwm.h
src/dpwm/sbc/dpwm.cpp