My Project: DDCMotor Class Reference
DDCMotor Class Reference
#include <ddcmotor.h>
Public Types
enum DControlMode { PWM_PWM , DIR_PWM }
enum DRotationDir { ROT_CC , ROT_CW , ROT_NONE }
Public Member Functions
DDCMotor ()
Limit pwm value for minimum calibration value.
DDCMotor (unsigned short int PinDirPwm, unsigned short int PinPwm, DControlMode Mode=DIR_PWM)
Construct a new DDCMotor::DDCMotor object.
~DDCMotor ()
Destroy the DDCMotor::DDCMotor object.
void attach (void)
Initialize Hardware.
void detach (void)
Release hardware.
bool attached (void)
void SetCalLimitFw (unsigned short int MaxPwmFw)
Set PWM calibration for forward direction.
void SetCalLimitRev (unsigned short int MaxPwmRev)
Set PWM calibration for backward direction.
void ResetCalLimit (void)
Reset all PWM calibration values to default.
void ResetCalLimitRev (void)
Reset reverse PWM calibration value to default.
void ResetCalLimitFw (void)
Reset forward PWM calibration value to default.
unsigned short int GetCalLimitFw (void)
unsigned short int GetCalLimitRev (void)
void SetIncValue (unsigned short int Value)
Set step value used by functions for direct increment - decrecrement speed.
void SwappedDirMode (bool Enabled)
Swap level on PinDir when set rotation direction.
short int GetVel (void)
unsigned short int GetPwm (void)
Calculate real pwm value corresponding to CurrVel.
DRotationDir GetDir (void)
N.B.
void CW (unsigned short int Vel)
Runs motor in clockwise direction at specific speed value.
void CC (unsigned short int Vel)
Runs motor in counter clockwise direction at specific speed value.
void Stop (void)
Stop motor (set vel to 0).
void Brake (void)
Brake motor.
void SetVel (int Vel)
Run motor.
bool IsRunning (void)
unsigned short int GetPinPwm (void)
Get pin number that is only used as PWM.
unsigned short int GetPinDirPwm (void)
Get pin number that is use as DIR (in PHASE_ENABLED mode) or PWM (in IN_IN mode).
Public Attributes
uint16_t MAX_PWM_VALUE =255
Max vel value.
uint16_t MIN_CAL_PWM_VALUE =100
Max pwm value (255 is arduino max value for analogWrite()).
Static Public Attributes
static const uint8_t MAX_VEL =100
Protected Attributes
int CurrVel
DPwmOut * PwmOut1
DPwmOut * PwmOut2
unsigned short SwappedDir
bool Running
unsigned short int PwmLimitFw
unsigned short int PwmLimitRev
DControlMode ControlMode
unsigned short int CurrStepValue
Detailed Description
Definition at line 6 of file ddcmotor.h.
Member Enumeration Documentation
DControlMode
enum DDCMotor::DControlMode
Enumerator
PWM_PWM
DIR_PWM
Definition at line 9 of file ddcmotor.h.
DRotationDir
enum DDCMotor::DRotationDir
Enumerator
ROT_CC
ROT_CW
ROT_NONE
Definition at line 11 of file ddcmotor.h.
Constructor & Destructor Documentation
DDCMotor() [1/2]
DDCMotor::DDCMotor ()
Limit pwm value for minimum calibration value.
DDCMotor() [2/2]
DDCMotor::DDCMotor (unsigned short int PinPwm, unsigned short int PinDirPwm, DControlMode Mode = DIR_PWM)
Construct a new DDCMotor::DDCMotor object.
Parameters
PwmPin -> In DIR_PWM mode pin is xENABLE(PWM). In DIR_DIR mode pin is PWM pin.
DirPwmPin -> In DIR_PWM mode pin is xPHASE(DIR). In DIR_DIR mode pin is PWM pin.
Mode -> The DIR_PWM mode only 2 pin are used in pwm mode (use it with board like "Pololu DRV8825 Dual Motor Driver Kit"). The DIR_DIR mode all 4 pins are used in pwm mode.
Definition at line 22 of file ddcmotor.cpp.
References ControlMode, PwmOut1, PwmOut2, and Running.
~DDCMotor()
DDCMotor::~DDCMotor ()
Destroy the DDCMotor::DDCMotor object.
Definition at line 33 of file ddcmotor.cpp.
References detach().
Member Function Documentation
attach()
void DDCMotor::attach (void)
Initialize Hardware.
Must be called before use this class.
Definition at line 42 of file ddcmotor.cpp.
References DPwmOut::begin(), CurrStepValue, CurrVel, DEFAULT_STEP_VALUE, DPwmOut::getPeriodUs(), MAX_PWM_VALUE, MIN_CAL_PWM_VALUE, PWM_FREQ, PwmOut1, PwmOut2, ResetCalLimit(), Running, Stop(), and SwappedDir.
Referenced by DCMotorRunTest().
attached()
bool DDCMotor::attached (void)
Returns
true if hardware pins are initialized, otherwise false;
Definition at line 105 of file ddcmotor.cpp.
References DPwmOut::isReady(), PwmOut1, and PwmOut2.
Referenced by DDCMotorWheels::attach(), DCMotorRunTest(), DDCMotorWheels::DDCMotorWheels(), and detach().
Brake()
void DDCMotor::Brake (void)
Brake motor.
Output signals to pins for blocking motor.
Definition at line 389 of file ddcmotor.cpp.
References ControlMode, CurrVel, DPwmOut::low(), MAX_PWM_VALUE, PWM_PWM, PwmOut1, PwmOut2, Running, and DPwmOut::setMicros().
Referenced by DDCMotorWheels::DXBrake(), and DDCMotorWheels::SXBrake().
CC()
void DDCMotor::CC (unsigned short int Vel)
Runs motor in counter clockwise direction at specific speed value.
N.B. If Engaged is true the value is applied to motor, otherwise only CurrVel is set.
Parameters
Vel Speed value from 1 to 100. If Vel is 0 CurrVel is used.
Definition at line 237 of file ddcmotor.cpp.
References CurrVel, and SetVel().
CW()
void DDCMotor::CW (unsigned short int Vel)
Runs motor in clockwise direction at specific speed value.
N.B. If Engaged is true the value is applied to motor, otherwise only CurrVel is set.
Parameters
Vel Speed value from 1 to 100. If Vel is 0 CurrVel is used.
Definition at line 221 of file ddcmotor.cpp.
References CurrVel, and SetVel().
detach()
void DDCMotor::detach (void)
Release hardware.
Definition at line 89 of file ddcmotor.cpp.
References attached(), PwmOut1, PwmOut2, DPwmOut::release(), and Stop().
Referenced by ~DDCMotor().
GetCalLimitFw()
unsigned short int DDCMotor::GetCalLimitFw (void)
Returns
current forward PWM calibration value
Definition at line 154 of file ddcmotor.cpp.
References PwmLimitFw.
Referenced by DDCMotorWheels::GetBalancingFw(), and DDCMotorWheels::SetBalancingFw().
GetCalLimitRev()
unsigned short int DDCMotor::GetCalLimitRev (void)
Returns
current reverse PWM calibration value
Definition at line 162 of file ddcmotor.cpp.
References PwmLimitRev.
Referenced by DDCMotorWheels::GetBalancingRev(), and DDCMotorWheels::SetBalancingRev().
GetDir()
DDCMotor::DRotationDir DDCMotor::GetDir (void)
N.B.
Real rotation direction depends from motor connection, if your direction does not match, and you can not swap motor wires connection, use EnableDirSwapMode(true) to correct it.
Returns
ROT_CW for clocwWise direction, ROT_CC for counter-clockwise direction.
Definition at line 297 of file ddcmotor.cpp.
References CurrVel, ROT_CC, ROT_CW, and ROT_NONE.
GetPinDirPwm()
unsigned short int DDCMotor::GetPinDirPwm (void)
Get pin number that is use as DIR (in PHASE_ENABLED mode) or PWM (in IN_IN mode).
Returns
DIR / PWN pin number.
Definition at line 427 of file ddcmotor.cpp.
References DPwmOut::getPin(), and PwmOut2.
GetPinPwm()
unsigned short int DDCMotor::GetPinPwm (void)
Get pin number that is only used as PWM.
Returns
PWM pin number.
Definition at line 417 of file ddcmotor.cpp.
References DPwmOut::getPin(), and PwmOut1.
GetPwm()
unsigned short int DDCMotor::GetPwm (void)
Calculate real pwm value corresponding to CurrVel.
Returns
Current PWM value from 0 to PwmLimitFw (if running forward) or 0 to PwmLimitRev (if running reverse)
Definition at line 277 of file ddcmotor.cpp.
References CurrVel, map, MAX_VEL, PwmLimitFw, and PwmLimitRev.
Referenced by DDCMotorWheels::DXGetPwm(), and DDCMotorWheels::SXGetPwm().
GetVel()
short int DDCMotor::GetVel (void)
Returns
current motor vel (from -100 to 100)
Definition at line 146 of file ddcmotor.cpp.
References CurrVel.
IsRunning()
bool DDCMotor::IsRunning (void)
Returns
true if motor is running, otherwise false.
Definition at line 407 of file ddcmotor.cpp.
References Running.
Referenced by DDCMotorWheels::DXIsRunning(), and DDCMotorWheels::SXIsRunning().
ResetCalLimit()
void DDCMotor::ResetCalLimit (void)
Reset all PWM calibration values to default.
Definition at line 113 of file ddcmotor.cpp.
References ResetCalLimitFw(), and ResetCalLimitRev().
Referenced by attach(), and DDCMotorWheels::ResetBalancing().
ResetCalLimitFw()
void DDCMotor::ResetCalLimitFw (void)
Reset forward PWM calibration value to default.
Definition at line 122 of file ddcmotor.cpp.
References CurrVel, DEFAULT_CAL_LIMIT, PwmLimitFw, and SetVel().
Referenced by DDCMotorWheels::ResetBalancingFw(), ResetCalLimit(), and DDCMotorWheels::SetBalancingFw().
ResetCalLimitRev()
void DDCMotor::ResetCalLimitRev (void)
Reset reverse PWM calibration value to default.
Definition at line 134 of file ddcmotor.cpp.
References CurrVel, DEFAULT_CAL_LIMIT, PwmLimitRev, Running, and SetVel().
Referenced by DDCMotorWheels::ResetBalancingRev(), ResetCalLimit(), and DDCMotorWheels::SetBalancingRev().
SetCalLimitFw()
void DDCMotor::SetCalLimitFw (unsigned short int NewPwmLimitFw)
Set PWM calibration for forward direction.
PwmLimitFw value will be used as maximun value for motor in forward direction (vel set to 100).
Parameters
NewPwmLimitFw PWM value from MIN_CAL_LIMIT to MAX_PWM.
Definition at line 173 of file ddcmotor.cpp.
References CurrVel, MAX_PWM_VALUE, MIN_CAL_PWM_VALUE, PwmLimitFw, Running, and SetVel().
Referenced by DDCMotorWheels::SetBalancingFw().
SetCalLimitRev()
void DDCMotor::SetCalLimitRev (unsigned short int NewPwmLimitRev)
Set PWM calibration for backward direction.
PwmLimitFw value will be used as maximun value for motor in forward direction (vel set to 100).
Parameters
NewPwmLimitRev PWM value from MIN_CAL_LIMIT to MAX_PWM.
Definition at line 197 of file ddcmotor.cpp.
References CurrVel, MAX_PWM_VALUE, MIN_CAL_PWM_VALUE, PwmLimitRev, Running, and SetVel().
Referenced by DDCMotorWheels::SetBalancingRev().
SetIncValue()
void DDCMotor::SetIncValue (unsigned short int Value)
Set step value used by functions for direct increment - decrecrement speed.
Parameters
Value -> Valid step values: from 1 to MAX_VEL (a zero value is set to 1)
Definition at line 261 of file ddcmotor.cpp.
References CurrStepValue, and MAX_VEL.
Referenced by DDCMotorWheels::DDCMotorWheels(), and DDCMotorWheels::SetStepValue().
SetVel()
void DDCMotor::SetVel (int Speed)
Run motor.
Vel is value from -100 to 100 where positive values runs motor in forward direction and negatives ones runs motor in backward direction. A value of 0 stops motor.
Parameters
Vel -> Absolute velocity value for motor: from -100 to 100, 0 stops the motor.
Definition at line 325 of file ddcmotor.cpp.
References ControlMode, CurrVel, DPwmOut::high(), DPwmOut::low(), map, MAX_VEL, PWM_PWM, PwmLimitFw, PwmLimitRev, PwmOut1, PwmOut2, Running, DPwmOut::setMicros(), and SwappedDir.
Referenced by CC(), CW(), ResetCalLimitFw(), ResetCalLimitRev(), SetCalLimitFw(), SetCalLimitRev(), and Stop().
Stop()
void DDCMotor::Stop (void)
Stop motor (set vel to 0).
Definition at line 251 of file ddcmotor.cpp.
References SetVel().
Referenced by attach(), detach(), and main().
SwappedDirMode()
void DDCMotor::SwappedDirMode (bool Enabled)
Swap level on PinDir when set rotation direction.
Use it with argument set to true if your motor rotate in wrong direction.
Parameters
Enabled
Definition at line 308 of file ddcmotor.cpp.
References SwappedDir.
Member Data Documentation
ControlMode
DControlMode DDCMotor::ControlMode protected
Definition at line 66 of file ddcmotor.h.
Referenced by Brake(), DDCMotor(), and SetVel().
CurrStepValue
unsigned short int DDCMotor::CurrStepValue protected
Definition at line 67 of file ddcmotor.h.
Referenced by attach(), and SetIncValue().
CurrVel
int DDCMotor::CurrVel protected
Definition at line 55 of file ddcmotor.h.
Referenced by attach(), Brake(), CC(), CW(), GetDir(), GetPwm(), GetVel(), ResetCalLimitFw(), ResetCalLimitRev(), SetCalLimitFw(), SetCalLimitRev(), and SetVel().
MAX_PWM_VALUE
uint16_t DDCMotor::MAX_PWM_VALUE =255
Max vel value.
Definition at line 18 of file ddcmotor.h.
Referenced by attach(), Brake(), SetCalLimitFw(), and SetCalLimitRev().
MAX_VEL
const uint8_t DDCMotor::MAX_VEL =100 static
Definition at line 13 of file ddcmotor.h.
Referenced by DDCMotorWheels::DXSetVel(), GetPwm(), SetIncValue(), SetVel(), and DDCMotorWheels::SXSetVel().
MIN_CAL_PWM_VALUE
uint16_t DDCMotor::MIN_CAL_PWM_VALUE =100
Max pwm value (255 is arduino max value for analogWrite()).
Definition at line 19 of file ddcmotor.h.
Referenced by attach(), SetCalLimitFw(), and SetCalLimitRev().
PwmLimitFw
unsigned short int DDCMotor::PwmLimitFw protected
Definition at line 64 of file ddcmotor.h.
Referenced by GetCalLimitFw(), GetPwm(), ResetCalLimitFw(), SetCalLimitFw(), and SetVel().
PwmLimitRev
unsigned short int DDCMotor::PwmLimitRev protected
Definition at line 65 of file ddcmotor.h.
Referenced by GetCalLimitRev(), GetPwm(), ResetCalLimitRev(), SetCalLimitRev(), and SetVel().
PwmOut1
DPwmOut* DDCMotor::PwmOut1 protected
Definition at line 57 of file ddcmotor.h.
Referenced by attach(), attached(), Brake(), DDCMotor(), detach(), GetPinPwm(), and SetVel().
PwmOut2
DPwmOut* DDCMotor::PwmOut2 protected
Definition at line 58 of file ddcmotor.h.
Referenced by attach(), attached(), Brake(), DDCMotor(), detach(), GetPinDirPwm(), and SetVel().
Running
bool DDCMotor::Running protected
Definition at line 62 of file ddcmotor.h.
Referenced by attach(), Brake(), DDCMotor(), IsRunning(), ResetCalLimitRev(), SetCalLimitFw(), SetCalLimitRev(), and SetVel().
SwappedDir
unsigned short DDCMotor::SwappedDir protected
Definition at line 60 of file ddcmotor.h.
Referenced by attach(), SetVel(), and SwappedDirMode().
The documentation for this class was generated from the following files:
src/_ddcmotor/ddcmotor.h
src/_ddcmotor/ddcmotor.cpp