My Project: DDigitalButton Class Reference
DDigitalButton Class Reference
#include <DDigitalButton.h>
Public Types
enum State {
RELEASE , PRESS , PRESSED , LONG_PRESSED ,
LONG_PRESSING , DBL_PRESSED , DBL_PRESSING , RELEASED
}
enum DButtonState {
ERROR_STATE = -1 , RELEASE , PRESS , PRESSED ,
LONG_PRESSED , LONG_PRESSING , DBL_PRESSED , DBL_PRESSING ,
RELEASED
}
typedef void(* DCallback) (State)
typedef void(* DCallback) (DButtonState)
Public Member Functions
DDigitalButton (int DigitalPin, uint8_t PressedState=LOW, bool PullUp=true, unsigned int PressedMillis=100, unsigned int LongPressedMillis=1000, unsigned int DblPressSpeedMillis=100)
Constructor.
void SetEventCallback (DCallback EventCallback)
DDigitalButton::State Read (void)
operator DDigitalButton::State ()
DDigitalButton (int digitalPin, DGpioHandle gpioHandle=-1)
~DDigitalButton ()
Destroy the DDigitalButton::DDigitalButton object and free pin use.
bool begin (int pressedState=LOW, bool pullUp=true, unsigned int pressedMillis=100, unsigned int longPressedMillis=1000, unsigned int dblPressSpeedMillis=100)
Constructor.
void setEventCallback (DCallback eventCallback)
DDigitalButton::DButtonState read (void)
std::string getLastError (void)
operator DDigitalButton::DButtonState ()
Private Member Functions
void SetPinMode (uint8_t pinMode)
uint8_t ReadPin (void)
unsigned long NowMillis (void)
Private Attributes
uint8_t Pin
State CurrState
State PrevState
uint8_t StatePressed
unsigned long ReleaseMs
unsigned long PressMs
unsigned long PressedMs
unsigned long PressedDuration
unsigned long DblPressSpeedDuration
unsigned long LongPressedDuration
DCallback Callback
uint8_t pin
DButtonState currState
DButtonState prevState
int pressedLevel
unsigned long releaseMs
unsigned long pressMs
unsigned long pressedMs
unsigned long pressedDuration
unsigned long dblPressSpeedDuration
unsigned long longPressedDuration
DCallback callback
DGpioHandle handle
DResult lastResult
Detailed Description
Definition at line 46 of file DDigitalButton.h.
Member Typedef Documentation
DCallback [1/2]
typedef void(* DDigitalButton::DCallback) (DButtonState)
Definition at line 21 of file ddigitalbutton.h.
DCallback [2/2]
typedef void(* DDigitalButton::DCallback) (State)
Definition at line 59 of file DDigitalButton.h.
Member Enumeration Documentation
DButtonState
enum DDigitalButton::DButtonState
Enumerator
ERROR_STATE
RELEASE
PRESS
Release STATE: button is not in StatePressed state.
PRESSED
Press STATE: button is in StatePressed state.
LONG_PRESSED
Pressed TRIGGER: press-release after PressedMillis time.
LONG_PRESSING
Long pressed TRIGGER: button is kept pressed for longer than LongPressedMillis.
DBL_PRESSED
Long Pressing STATE: after LONG_PRESSED, if button still pressed, the state change in LONG_PRESSING until button is released.
DBL_PRESSING
Double pressed TRIGGER: press-release-press within DblPressSpeedMillis time.
RELEASED
Double pressing STATE: after DBL_PRESSED, if button still pressed, the state change in DBL_PRESSING until button is released.
Released TRIGGER: release after PRESSED, LONG_PRESSED, DBL_PRESSED.
Definition at line 9 of file ddigitalbutton.h.
State
enum DDigitalButton::State
Enumerator
RELEASE
PRESS
Release STATE: button is not in StatePressed state.
PRESSED
Press STATE: button is in StatePressed state.
LONG_PRESSED
Pressed TRIGGER: press-release after PressedMillis time.
LONG_PRESSING
Long pressed TRIGGER: button is kept pressed for longer than LongPressedMillis.
DBL_PRESSED
Long Pressing STATE: after LONG_PRESSED, if button still pressed, the state change in LONG_PRESSING until button is released.
DBL_PRESSING
Double pressed TRIGGER: press-release-press within DblPressSpeedMillis time.
RELEASED
Double pressing STATE: after DBL_PRESSED, if button still pressed, the state change in DBL_PRESSING until button is released.
Released TRIGGER: release after PRESSED, LONG_PRESSED, DBL_PRESSED.
Definition at line 49 of file DDigitalButton.h.
Constructor & Destructor Documentation
DDigitalButton() [1/2]
DDigitalButton::DDigitalButton (int DigitalPin, uint8_t PressedState = LOW, bool PullUp = true, unsigned int PressedMillis = 100, unsigned int LongPressedMillis = 1000, unsigned int DblPressSpeedMillis = 100)
Constructor.
Parameters
DigitalPin -> Pin number where button is connected.
PressedState -> Can be HIGH or LOW and it is the pin level for which the button is considered to be pressed.
PullUp -> If true the internal pull-up resistor is connected.
PressedMillis -> Time in milliseconds after which "press and release" is triggered as PRESSED.
LongPressedMillis -> Time in milliseconds after which a "keeping press" is triggered as LONG_PRESSED.
DblPressSpeedMillis -> Time in milliseconds before which "press, release, press" is triggered as DBL_PRESSED.
Definition at line 40 of file DDigitalButton.cpp.
References Callback, DblPressSpeedDuration, INPUT, INPUT_PULLUP, LongPressedDuration, NowMillis(), Pin, PressedDuration, PressedMs, PressMs, Read(), ReleaseMs, SetPinMode(), and StatePressed.
DDigitalButton() [2/2]
DDigitalButton::DDigitalButton (int digitalPin, DGpioHandle gpioHandle = -1)
Definition at line 31 of file ddigitalbutton.cpp.
References DERR_CLASS_NOT_BEGUN, DERR_GPIO_NOT_READY, DRES_OK, handle, initGpio(), isGpioReady(), lastResult, and pin.
~DDigitalButton()
DDigitalButton::~DDigitalButton ()
Destroy the DDigitalButton::DDigitalButton object and free pin use.
Definition at line 58 of file ddigitalbutton.cpp.
References handle, pin, and releasePin().
Member Function Documentation
begin()
bool DDigitalButton::begin (int pressedState = LOW, bool pullUp = true, unsigned int pressedMillis = 100, unsigned int longPressedMillis = 1000, unsigned int dblPressSpeedMillis = 100)
Constructor.
Parameters
digitalPin -> gpio pin.
pressedState -> The level for which the button "is considered pressed", be HIGH or LOW.
pullUp -> If true the internal pull-up resistor is connected.
pressedMillis -> Time in milliseconds after which "press and release" is triggered as PRESSED.
longPressedMillis -> Time in milliseconds after which a "keeping press" is triggered as LONG_PRESSED.
dblPressSpeedMillis -> Time in milliseconds before which "press, release, press" is triggered as DBL_PRESSED.
Definition at line 72 of file ddigitalbutton.cpp.
References callback, dblPressSpeedDuration, DRES_OK, handle, initPin(), INPUT, INPUT_PULLUP, lastResult, longPressedDuration, millis(), NO_FLAGS, pin, pressedDuration, pressedLevel, pressedMs, pressMs, read(), and releaseMs.
getLastError()
std::string DDigitalButton::getLastError (void)
NowMillis()
unsigned long DDigitalButton::NowMillis (void) private
Referenced by DDigitalButton().
operator DDigitalButton::DButtonState()
DDigitalButton::operator DDigitalButton::DButtonState ()
operator DDigitalButton::State()
DDigitalButton::operator DDigitalButton::State ()
Read()
DDigitalButton::State DDigitalButton::Read (void)
Referenced by DCMotorRunTest(), DDigitalButton(), loop(), and ServoRunTest().
read()
DDigitalButton::DButtonState DDigitalButton::read (void)
Referenced by begin().
ReadPin()
uint8_t DDigitalButton::ReadPin (void) private
SetEventCallback()
void DDigitalButton::SetEventCallback (DCallback EventCallback)
setEventCallback()
void DDigitalButton::setEventCallback (DCallback eventCallback)
SetPinMode()
void DDigitalButton::SetPinMode (uint8_t pinMode) private
Referenced by DDigitalButton().
Member Data Documentation
Callback
DCallback DDigitalButton::Callback private
Definition at line 82 of file DDigitalButton.h.
Referenced by DDigitalButton().
callback
DCallback DDigitalButton::callback private
Definition at line 46 of file ddigitalbutton.h.
Referenced by begin().
CurrState
State DDigitalButton::CurrState private
Definition at line 71 of file DDigitalButton.h.
currState
DButtonState DDigitalButton::currState private
Definition at line 35 of file ddigitalbutton.h.
DblPressSpeedDuration
unsigned long DDigitalButton::DblPressSpeedDuration private
Definition at line 80 of file DDigitalButton.h.
Referenced by DDigitalButton().
dblPressSpeedDuration
unsigned long DDigitalButton::dblPressSpeedDuration private
Definition at line 44 of file ddigitalbutton.h.
Referenced by begin().
handle
DGpioHandle DDigitalButton::handle private
Definition at line 48 of file ddigitalbutton.h.
Referenced by begin(), DDigitalButton(), and ~DDigitalButton().
lastResult
DResult DDigitalButton::lastResult private
Definition at line 49 of file ddigitalbutton.h.
Referenced by begin(), and DDigitalButton().
LongPressedDuration
unsigned long DDigitalButton::LongPressedDuration private
Definition at line 81 of file DDigitalButton.h.
Referenced by DDigitalButton().
longPressedDuration
unsigned long DDigitalButton::longPressedDuration private
Definition at line 45 of file ddigitalbutton.h.
Referenced by begin().
Pin
uint8_t DDigitalButton::Pin private
Definition at line 70 of file DDigitalButton.h.
Referenced by DDigitalButton().
pin
uint8_t DDigitalButton::pin private
Definition at line 34 of file ddigitalbutton.h.
Referenced by begin(), DDigitalButton(), and ~DDigitalButton().
PressedDuration
unsigned long DDigitalButton::PressedDuration private
Definition at line 79 of file DDigitalButton.h.
Referenced by DDigitalButton().
pressedDuration
unsigned long DDigitalButton::pressedDuration private
Definition at line 43 of file ddigitalbutton.h.
Referenced by begin().
pressedLevel
int DDigitalButton::pressedLevel private
Definition at line 37 of file ddigitalbutton.h.
Referenced by begin().
PressedMs
unsigned long DDigitalButton::PressedMs private
Definition at line 77 of file DDigitalButton.h.
Referenced by DDigitalButton().
pressedMs
unsigned long DDigitalButton::pressedMs private
Definition at line 41 of file ddigitalbutton.h.
Referenced by begin().
PressMs
unsigned long DDigitalButton::PressMs private
Definition at line 76 of file DDigitalButton.h.
Referenced by DDigitalButton().
pressMs
unsigned long DDigitalButton::pressMs private
Definition at line 40 of file ddigitalbutton.h.
Referenced by begin().
PrevState
State DDigitalButton::PrevState private
Definition at line 72 of file DDigitalButton.h.
prevState
DButtonState DDigitalButton::prevState private
Definition at line 36 of file ddigitalbutton.h.
ReleaseMs
unsigned long DDigitalButton::ReleaseMs private
Definition at line 75 of file DDigitalButton.h.
Referenced by DDigitalButton().
releaseMs
unsigned long DDigitalButton::releaseMs private
Definition at line 39 of file ddigitalbutton.h.
Referenced by begin().
StatePressed
uint8_t DDigitalButton::StatePressed private
Definition at line 73 of file DDigitalButton.h.
Referenced by DDigitalButton().
The documentation for this class was generated from the following files:
examples/_ddigitalbutton/arduino-ide-ddigitalbutton-demo/DDigitalButton.h
examples/_ddigitalbutton/arduino-ide-ddigitalbutton-demo/DDigitalButton.cpp