My Project: DDCMotorWheels Class Reference
DDCMotorWheels Class Reference
#include <DDCMotorWheels.h>
Public Types
enum DBalanceValues { MAX_SX =-DDCMotor::MIN_CAL_PWM , MAX_DX =DDCMotor::MAX_PWM }
Public Member Functions
DDCMotorWheels ()
Construct a new DDCMotorWheels::DDCMotorWheels object.
DDCMotorWheels (unsigned short int SXPwmPin, unsigned short int SXDirPwmPin, unsigned short int DXPwmPin, unsigned short int DXDirPwmPin, DDCMotor::DControlMode Mode=DDCMotor::DIR_PWM)
Construct a new DDCMotorWheels::DDCMotorWheels object and initialize motors.
DDCMotorWheels (DDCMotor *SXMotor, DDCMotor *DXMotor)
Construct a new DDCMotorWheels::DDCMotorWheels object using previously created DDCMotor objects.
~DDCMotorWheels ()
Destroy the DDCMotorWheels::DDCMotorWheels object.
void attach (unsigned short int SXPwmPin, unsigned short int SXDirPin, unsigned short int DXPwmPin, unsigned short int DXDirPwmPin, DDCMotor::DControlMode Mode=DDCMotor::DIR_PWM)
Initialize hardware pins for motores.
void detach (void)
Free hardware resources.
bool attached (void)
void engage (bool Engage=true)
Engage/disengage motors.
void disengage (void)
Disengage motors.
bool engaged (void)
void SetBalancingFw (short int Value)
Set wheels balancing value for forward direction.
void SetBalancingRev (short int Value)
Set wheels balancing value for backward direction.
void MoveBalancingFwSX (unsigned short int Value)
Move balancing FW to SX by Value.
void MoveBalancingFwDX (unsigned short int Value)
Move balancing FW to DX by Value.
void MoveBalancingRevSX (unsigned short int Value)
Move balancing REV to SX by Value.
void MoveBalancingRevDX (unsigned short int Value)
Move balancing REV to DX by Value.
short int GetBalancingFw (void)
short int GetBalancingRev (void)
void ResetBalancingFw (void)
Reset balancing value for forward direction to 0.
void ResetBalancingRev (void)
Reset balancing value for backward direction to 0.
void ResetBalancing (void)
Reset all balancing values to 0.
short int SXGetVel (void)
short int SXGetPwm (void)
short int DXGetVel (void)
short int DXGetPwm (void)
bool SXIsRunning (void)
bool DXIsRunning (void)
void SXFw (unsigned short int Vel=0)
Runs sx motor in forward direction at specific speed value.
void DXFw (unsigned short int Vel=0)
Runs dx motor in forward direction at specific speed value.
void Fw (unsigned short int Vel=0)
Runs both motors in forward direction at specific speed value.
void SXRev (unsigned short int Vel=0)
Runs sx motor in backward direction at specific speed value.
void DXRev (unsigned short int Vel=0)
Runs dx motor in backward direction at specific speed value.
void Rev (unsigned short int Vel=0)
Runs both motors in backward direction at specific speed value.
void SXStop (void)
Stop sx motor (set vel to 0)
void DXStop (void)
Stop dx motor (set vel to 0)
void Stop (void)
Stop both motor (set vel to 0)
void SXBrake (void)
Brake sx motor (set pins level to brake motor)
void DXBrake (void)
Brake dx motor (set pins level to brake motor)
void Brake (void)
Brake both motor (set pins level to brake motors)
void SXIncVel (unsigned short int Value=0)
Increment sx motor speed by specific value.
void SXDecVel (unsigned short int Value=0)
Decrement sx motor speed by specific value.
void DXIncVel (unsigned short int Value=0)
Increment dx motor speed by specific value.
void DXDecVel (unsigned short int Value=0)
Decrement dx motor speed by specific value.
void IncVel (unsigned short int Value=0)
Increment both motors speed by specific value.
void DecVel (unsigned short int Value=0)
Decrement both motors speed by specific value.
void SetStepValue (unsigned short int Value)
Set step value used by functions for direct increment - decrecrement speed.
void SXSetVel (short int Vel)
Set velocity value for sx motor.
void DXSetVel (short int Vel)
Set velocity value for dx motor.
void SetVel (short int SXVel, short int DXVel)
Set absolute vel values for both motors.
Public Attributes
DDCMotor * MotorSX
DDCMotor * MotorDX
Private Attributes
bool Attached
bool Engaged
short int CurrSXVel
short int CurrDXVel
unsigned short int CurrStepValue
Detailed Description
Definition at line 6 of file DDCMotorWheels.h.
Member Enumeration Documentation
DBalanceValues
enum DDCMotorWheels::DBalanceValues
Enumerator
MAX_SX
MAX_DX
Definition at line 11 of file DDCMotorWheels.h.
Constructor & Destructor Documentation
DDCMotorWheels() [1/3]
DDCMotorWheels::DDCMotorWheels ()
Construct a new DDCMotorWheels::DDCMotorWheels object.
Use attach() function to init motors.
Definition at line 20 of file DDCMotorWheels.cpp.
References Attached, CurrDXVel, CurrStepValue, CurrSXVel, DEFAULT_INCREMENTAL_VALUE, Engaged, MotorDX, and MotorSX.
DDCMotorWheels() [2/3]
DDCMotorWheels::DDCMotorWheels (unsigned short int SXPwmPin, unsigned short int SXDirPwmPin, unsigned short int DXPwmPin, unsigned short int DXDirPwmPin, DDCMotor::DControlMode Mode = DDCMotor::DIR_PWM)
Construct a new DDCMotorWheels::DDCMotorWheels object and initialize motors.
Parameters
SXPwmPin -> In PHASE_ENABLE mode pin is xENABLE(PWM). In IN_IN mode pin is PWM pin.
SXDirPwmPin -> In PHASE_ENABLE mode pin is xPHASE(DIR). In IN_IN mode pin is PWM pin.
DXPwmPin -> In PHASE_ENABLE mode pin is xENABLE(PWM). In IN_IN mode pin is PWM pin.
DXDirPwmPin -> In PHASE_ENABLE mode pin is xPHASE(DIR). In IN_IN mode pin is PWM pin.
Mode -> The IN_IN mode all 4 pins are used in pwm mode. The PHASE_ENABLE mode only 2 pin are used pwm mode (use it with board like "Pololu DRV8825 Dual Motor Driver Kit")
Definition at line 45 of file DDCMotorWheels.cpp.
References attach(), Attached, CurrDXVel, CurrStepValue, CurrSXVel, DEFAULT_INCREMENTAL_VALUE, Engaged, MotorDX, and MotorSX.
DDCMotorWheels() [3/3]
DDCMotorWheels::DDCMotorWheels (DDCMotor * SXMotor, DDCMotor * DXMotor)
Construct a new DDCMotorWheels::DDCMotorWheels object using previously created DDCMotor objects.
WARNING: both DDCMotor objects will be deleted when this class will be destroyed or when detach() function is called.
Parameters
SXMotor -> Pointer to DDCMotor object for sx wheels.
DXMotor -> Pointer to DDCMotor object for dx wheels.
Definition at line 64 of file DDCMotorWheels.cpp.
References DDCMotor::attached(), Attached, CurrStepValue, DEFAULT_INCREMENTAL_VALUE, Engaged, MotorDX, MotorSX, and DDCMotor::SetIncValue().
~DDCMotorWheels()
DDCMotorWheels::~DDCMotorWheels ()
Destroy the DDCMotorWheels::DDCMotorWheels object.
Definition at line 79 of file DDCMotorWheels.cpp.
References Attached, MotorDX, and MotorSX.
Member Function Documentation
attach()
void DDCMotorWheels::attach (unsigned short int SXPwmPin, unsigned short int SXDirPwmPin, unsigned short int DXPwmPin, unsigned short int DXDirPwmPin, DDCMotor::DControlMode Mode = DDCMotor::DIR_PWM)
Initialize hardware pins for motores.
Parameters
SXPwmPin -> In PHASE_ENABLE mode pin is xENABLE(PWM). In IN_IN mode pin is PWM pin.
SXDirPwmPin -> In PHASE_ENABLE mode pin is xPHASE(DIR). In IN_IN mode pin is PWM pin.
DXPwmPin -> In PHASE_ENABLE mode pin is xENABLE(PWM). In IN_IN mode pin is PWM pin.
DXDirPwmPin -> In PHASE_ENABLE mode pin is xPHASE(DIR). In IN_IN mode pin is PWM pin.
Mode -> The IN_IN mode all 4 pins are used in pwm mode. The PHASE_ENABLE mode only 2 pin are used pwm mode (use it with board like "Pololu DRV8825 Dual Motor Driver Kit")
Definition at line 101 of file DDCMotorWheels.cpp.
References DDCMotor::attached(), Attached, CurrDXVel, CurrSXVel, detach(), MotorDX, and MotorSX.
Referenced by DDCMotorWheels().
attached()
bool DDCMotorWheels::attached (void)
Returns
true if hardware pins are correctly set.
Definition at line 413 of file DDCMotorWheels.cpp.
References Attached.
Brake()
void DDCMotorWheels::Brake (void)
Brake both motor (set pins level to brake motors)
Definition at line 563 of file DDCMotorWheels.cpp.
References DXBrake(), and SXBrake().
DecVel()
void DDCMotorWheels::DecVel (unsigned short int Value = 0)
Decrement both motors speed by specific value.
N.B. If Engaged is true the value is applied to motors, otherwise only values are set.
Parameters
Value -> Step value, if Value is 0 CurrStepValue is used.
Definition at line 587 of file DDCMotorWheels.cpp.
References DXDecVel(), and SXDecVel().
detach()
void DDCMotorWheels::detach (void)
Free hardware resources.
Definition at line 116 of file DDCMotorWheels.cpp.
References Attached, Engaged, MotorDX, and MotorSX.
Referenced by attach().
disengage()
void DDCMotorWheels::disengage (void)
Disengage motors.
N.B. If motors are runnings, they will be stopped.
Definition at line 434 of file DDCMotorWheels.cpp.
References engage().
DXBrake()
void DDCMotorWheels::DXBrake (void)
Brake dx motor (set pins level to brake motor)
Definition at line 353 of file DDCMotorWheels.cpp.
References DDCMotor::Brake(), and MotorDX.
Referenced by Brake().
DXDecVel()
void DDCMotorWheels::DXDecVel (unsigned short int Value = 0)
Decrement dx motor speed by specific value.
N.B. If Engaged is true the value is applied to motor, otherwise only CurrDXVel is set.
Parameters
Value -> Step value, if Value is 0 CurrStepValue is used.
Definition at line 655 of file DDCMotorWheels.cpp.
References CurrDXVel, CurrStepValue, and DXSetVel().
Referenced by DecVel().
DXFw()
void DDCMotorWheels::DXFw (unsigned short int Vel = 0)
Runs dx motor in forward direction at specific speed value.
N.B. If Engaged is true the value is applied to motor, otherwise only CurrDXVel is set.
Parameters
Vel Speed value from 1 to 100. If Vel is 0 CurrDXVel is used.
Definition at line 485 of file DDCMotorWheels.cpp.
References CurrDXVel, and DXSetVel().
Referenced by Fw().
DXGetPwm()
short int DDCMotorWheels::DXGetPwm (void)
Returns
Current PWM value for dx motor.
Definition at line 372 of file DDCMotorWheels.cpp.
References DDCMotor::GetPwm(), and MotorSX.
DXGetVel()
short int DDCMotorWheels::DXGetVel (void)
Returns
Current dx motor vel value (from -100 to 100).
Definition at line 458 of file DDCMotorWheels.cpp.
References CurrDXVel.
DXIncVel()
void DDCMotorWheels::DXIncVel (unsigned short int Value = 0)
Increment dx motor speed by specific value.
N.B. If Engaged is true the value is applied to motor, otherwise only CurrDXVel is set.
Parameters
Value -> Step value, if Value is 0 CurrStepValue is used.
Definition at line 636 of file DDCMotorWheels.cpp.
References CurrDXVel, CurrStepValue, and DXSetVel().
Referenced by IncVel().
DXIsRunning()
bool DDCMotorWheels::DXIsRunning (void)
Returns
true if dx motor is running.
Definition at line 388 of file DDCMotorWheels.cpp.
References DDCMotor::IsRunning(), and MotorDX.
DXRev()
void DDCMotorWheels::DXRev (unsigned short int Vel = 0)
Runs dx motor in backward direction at specific speed value.
N.B. If Engaged is true the value is applied to motor, otherwise only CurrDXVel is set.
Parameters
Vel Speed value from 1 to 100. If Vel is 0 CurrDXVel is used.
Definition at line 517 of file DDCMotorWheels.cpp.
References CurrDXVel, and DXSetVel().
Referenced by Rev().
DXSetVel()
void DDCMotorWheels::DXSetVel (short int Vel)
Set velocity value for dx motor.
N.B. If Engaged is true the value is applied to motor, otherwise only CurrSXVel is set.
Parameters
Vel -> Absolute velocity value from -100 to 100. A value of 0 stops the motor.
Definition at line 312 of file DDCMotorWheels.cpp.
References CurrDXVel, Engaged, DDCMotor::MAX_VEL, and MotorDX.
Referenced by DXDecVel(), DXFw(), DXIncVel(), DXRev(), DXStop(), and SetVel().
DXStop()
void DDCMotorWheels::DXStop (void)
Stop dx motor (set vel to 0)
Definition at line 337 of file DDCMotorWheels.cpp.
References DXSetVel().
Referenced by Stop().
engage()
void DDCMotorWheels::engage (bool Engage = true)
Engage/disengage motors.
Parameters
Engage -> If true all changes of CurrSXVel and CurrDXVel are applied to the motors, otherwise only values are set. N.B. If Engaged is false and motors are runnings, they will be stopped.
Definition at line 424 of file DDCMotorWheels.cpp.
References Engaged, and Stop().
Referenced by disengage().
engaged()
bool DDCMotorWheels::engaged (void)
Returns
true if motors are engaged.
Definition at line 442 of file DDCMotorWheels.cpp.
References Engaged.
Fw()
void DDCMotorWheels::Fw (unsigned short int Vel = 0)
Runs both motors in forward direction at specific speed value.
N.B. If Engaged is true the value is applied to motors, otherwise only values are set.
Parameters
Vel Speed value from 1 to 100. If Vel is 0 current vel are used.
Definition at line 533 of file DDCMotorWheels.cpp.
References DXFw(), and SXFw().
GetBalancingFw()
short int DDCMotorWheels::GetBalancingFw (void)
Returns
Currently balancing value for forward direction.
Definition at line 396 of file DDCMotorWheels.cpp.
References DDCMotor::GetCalLimitFw(), MotorDX, and MotorSX.
Referenced by MoveBalancingFwDX(), and MoveBalancingFwSX().
GetBalancingRev()
short int DDCMotorWheels::GetBalancingRev (void)
Returns
Currently balancing value for backward direction.
Definition at line 404 of file DDCMotorWheels.cpp.
References DDCMotor::GetCalLimitRev(), MotorDX, and MotorSX.
Referenced by MoveBalancingRevDX(), and MoveBalancingRevSX().
IncVel()
void DDCMotorWheels::IncVel (unsigned short int Value = 0)
Increment both motors speed by specific value.
N.B. If Engaged is true the value is applied to motors, otherwise only values are set.
Parameters
Value -> Step value, if Value is 0 CurrStepValue is used.
Definition at line 575 of file DDCMotorWheels.cpp.
References DXIncVel(), and SXIncVel().
MoveBalancingFwDX()
void DDCMotorWheels::MoveBalancingFwDX (unsigned short int Value)
Move balancing FW to DX by Value.
Parameters
Value -> from 1 to 255 (default 1)
Definition at line 180 of file DDCMotorWheels.cpp.
References GetBalancingFw(), and SetBalancingFw().
MoveBalancingFwSX()
void DDCMotorWheels::MoveBalancingFwSX (unsigned short int Value)
Move balancing FW to SX by Value.
Parameters
Value -> from 1 to 255 (default 1)
Definition at line 170 of file DDCMotorWheels.cpp.
References GetBalancingFw(), and SetBalancingFw().
MoveBalancingRevDX()
void DDCMotorWheels::MoveBalancingRevDX (unsigned short int Value)
Move balancing REV to DX by Value.
Parameters
Value -> from 1 to 255 (default 1)
Definition at line 200 of file DDCMotorWheels.cpp.
References GetBalancingRev(), and SetBalancingRev().
MoveBalancingRevSX()
void DDCMotorWheels::MoveBalancingRevSX (unsigned short int Value)
Move balancing REV to SX by Value.
Parameters
Value -> from 1 to 255 (default 1)
Definition at line 190 of file DDCMotorWheels.cpp.
References GetBalancingRev(), and SetBalancingRev().
ResetBalancing()
void DDCMotorWheels::ResetBalancing (void)
Reset all balancing values to 0.
Definition at line 249 of file DDCMotorWheels.cpp.
References MotorDX, MotorSX, and DDCMotor::ResetCalLimit().
ResetBalancingFw()
void DDCMotorWheels::ResetBalancingFw (void)
Reset balancing value for forward direction to 0.
Definition at line 259 of file DDCMotorWheels.cpp.
References MotorDX, MotorSX, and DDCMotor::ResetCalLimitFw().
ResetBalancingRev()
void DDCMotorWheels::ResetBalancingRev (void)
Reset balancing value for backward direction to 0.
Definition at line 269 of file DDCMotorWheels.cpp.
References MotorDX, MotorSX, and DDCMotor::ResetCalLimitRev().
Rev()
void DDCMotorWheels::Rev (unsigned short int Vel = 0)
Runs both motors in backward direction at specific speed value.
N.B. If Engaged is true the value is applied to motors, otherwise only values are set.
Parameters
Vel Speed value from 1 to 100. If Vel is 0 current vel are used.
Definition at line 545 of file DDCMotorWheels.cpp.
References DXRev(), and SXRev().
SetBalancingFw()
void DDCMotorWheels::SetBalancingFw (short int Value)
Set wheels balancing value for forward direction.
A negative value means that sx wheel runs faster than dx, so, MotorDX::PwmLimitFw will decrease (but not under DMotor::MIN_CAL_PWM). A positive value means that dx wheel runs faster than sx, so, MotorSX::PwmLimitFw will decrease (but not under DMotor::MIN_CAL_PWM). A zero value means that sx and dx wheel runs without compensation.
Parameters
Value -> from -[DDCMotor::MAX_PWM-DDCMotor::MIN_CAL_PWM] to [DDCMotor::MAX_PWM-DDCMotor::MIN_CAL_PWM]. Default: -155 to 155
Definition at line 134 of file DDCMotorWheels.cpp.
References DDCMotor::GetCalLimitFw(), MotorDX, MotorSX, DDCMotor::ResetCalLimitFw(), and DDCMotor::SetCalLimitFw().
Referenced by MoveBalancingFwDX(), and MoveBalancingFwSX().
SetBalancingRev()
void DDCMotorWheels::SetBalancingRev (short int Value)
Set wheels balancing value for backward direction.
A negative value means that sx wheel runs faster than dx. A positive value means that dx wheel runs faster than sx. A zero value means that sx and dx wheel runs without compensation.
Parameters
Value -> from -[DDCMotor::MAX_PWM-DDCMotor::MIN_CAL_PWM] to [DDCMotor::MAX_PWM-DDCMotor::MIN_CAL_PWM]. Default: -155 to 155
Definition at line 213 of file DDCMotorWheels.cpp.
References DDCMotor::GetCalLimitRev(), MotorDX, MotorSX, DDCMotor::ResetCalLimitRev(), and DDCMotor::SetCalLimitRev().
Referenced by MoveBalancingRevDX(), and MoveBalancingRevSX().
SetStepValue()
void DDCMotorWheels::SetStepValue (unsigned short int Value)
Set step value used by functions for direct increment - decrecrement speed.
Parameters
Value -> Valid step values: from 1 to MAX_VEL (a zero value is set to 1)
Definition at line 280 of file DDCMotorWheels.cpp.
References MotorDX, MotorSX, and DDCMotor::SetIncValue().
SetVel()
void DDCMotorWheels::SetVel (short int SXVel, short int DXVel)
Set absolute vel values for both motors.
Set -100 for full reverse speed. Set 100 for full forward speed. Set 0 to stop. N.B. If Engaged is true the value is applied to motors, otherwise only values are set.
Parameters
SXValue -> Absolute velocity value for sx motor: from -100 to 100, 0 for stop.
DXValue -> Absolute velocity value for dx motor: from -100 to 100, 0 for stop.
es:
Set(50,-100); // SX motor forward at 50% and DX motor reverse at 100%.
Definition at line 682 of file DDCMotorWheels.cpp.
References DXSetVel(), and SXSetVel().
Stop()
void DDCMotorWheels::Stop (void)
Stop both motor (set vel to 0)
Definition at line 554 of file DDCMotorWheels.cpp.
References DXStop(), and SXStop().
Referenced by engage().
SXBrake()
void DDCMotorWheels::SXBrake (void)
Brake sx motor (set pins level to brake motor)
Definition at line 345 of file DDCMotorWheels.cpp.
References DDCMotor::Brake(), and MotorSX.
Referenced by Brake().
SXDecVel()
void DDCMotorWheels::SXDecVel (unsigned short int Value = 0)
Decrement sx motor speed by specific value.
N.B. If Engaged is true the value is applied to motor, otherwise only CurrSXVel is set.
Parameters
Value -> step value, if Value is 0 CurrStepValue is used.
Definition at line 618 of file DDCMotorWheels.cpp.
References CurrStepValue, CurrSXVel, and SXSetVel().
Referenced by DecVel().
SXFw()
void DDCMotorWheels::SXFw (unsigned short int Vel = 0)
Runs sx motor in forward direction at specific speed value.
N.B. If Engaged is true the value is applied to motor, otherwise only CurrSXVel is set.
Parameters
Vel Speed value from 1 to 100. If Vel is 0 CurrSXVel is used.
Definition at line 469 of file DDCMotorWheels.cpp.
References CurrSXVel, and SXSetVel().
Referenced by Fw().
SXGetPwm()
short int DDCMotorWheels::SXGetPwm (void)
Returns
Current PWM value for sx motor.
Definition at line 364 of file DDCMotorWheels.cpp.
References DDCMotor::GetPwm(), and MotorSX.
SXGetVel()
short int DDCMotorWheels::SXGetVel (void)
Returns
Current sx motor vel value (from -100 to 100).
Definition at line 450 of file DDCMotorWheels.cpp.
References CurrSXVel.
SXIncVel()
void DDCMotorWheels::SXIncVel (unsigned short int Value = 0)
Increment sx motor speed by specific value.
N.B. If Engaged is true the value is applied to motor, otherwise only CurrSXVel is set.
Parameters
Value -> Step value, if Value is 0 CurrStepValue is used.
Definition at line 599 of file DDCMotorWheels.cpp.
References CurrStepValue, CurrSXVel, and SXSetVel().
Referenced by IncVel().
SXIsRunning()
bool DDCMotorWheels::SXIsRunning (void)
Returns
true if sx motor is running.
Definition at line 380 of file DDCMotorWheels.cpp.
References DDCMotor::IsRunning(), and MotorSX.
SXRev()
void DDCMotorWheels::SXRev (unsigned short int Vel = 0)
Runs sx motor in backward direction at specific speed value.
N.B. If Engaged is true the value is applied to motor, otherwise only CurrSXVel is set.
Parameters
Vel Speed value from 1 to 100. If Vel is 0 CurrSXVel is used.
Definition at line 501 of file DDCMotorWheels.cpp.
References CurrSXVel, and SXSetVel().
Referenced by Rev().
SXSetVel()
void DDCMotorWheels::SXSetVel (short int Vel)
Set velocity value for sx motor.
N.B. If Engaged is true the value is applied to motor, otherwise only CurrSXVel is set.
Parameters
Vel -> Absolute velocity value from -100 to 100. A value of 0 stops the motor.
Definition at line 292 of file DDCMotorWheels.cpp.
References CurrSXVel, Engaged, DDCMotor::MAX_VEL, and MotorSX.
Referenced by SetVel(), SXDecVel(), SXFw(), SXIncVel(), SXRev(), and SXStop().
SXStop()
void DDCMotorWheels::SXStop (void)
Stop sx motor (set vel to 0)
Definition at line 329 of file DDCMotorWheels.cpp.
References SXSetVel().
Referenced by Stop().
Member Data Documentation
Attached
bool DDCMotorWheels::Attached private
Definition at line 83 of file DDCMotorWheels.h.
Referenced by attach(), attached(), DDCMotorWheels(), detach(), and ~DDCMotorWheels().
CurrDXVel
short int DDCMotorWheels::CurrDXVel private
Definition at line 86 of file DDCMotorWheels.h.
Referenced by attach(), DDCMotorWheels(), DXDecVel(), DXFw(), DXGetVel(), DXIncVel(), DXRev(), and DXSetVel().
CurrStepValue
unsigned short int DDCMotorWheels::CurrStepValue private
Definition at line 87 of file DDCMotorWheels.h.
Referenced by DDCMotorWheels(), DXDecVel(), DXIncVel(), SXDecVel(), and SXIncVel().
CurrSXVel
short int DDCMotorWheels::CurrSXVel private
Definition at line 85 of file DDCMotorWheels.h.
Referenced by attach(), DDCMotorWheels(), SXDecVel(), SXFw(), SXGetVel(), SXIncVel(), SXRev(), and SXSetVel().
Engaged
bool DDCMotorWheels::Engaged private
Definition at line 84 of file DDCMotorWheels.h.
Referenced by DDCMotorWheels(), detach(), DXSetVel(), engage(), engaged(), and SXSetVel().
MotorDX
DDCMotor* DDCMotorWheels::MotorDX
Definition at line 80 of file DDCMotorWheels.h.
Referenced by attach(), DDCMotorWheels(), detach(), DXBrake(), DXIsRunning(), DXSetVel(), GetBalancingFw(), GetBalancingRev(), ResetBalancing(), ResetBalancingFw(), ResetBalancingRev(), SetBalancingFw(), SetBalancingRev(), SetStepValue(), and ~DDCMotorWheels().
MotorSX
DDCMotor* DDCMotorWheels::MotorSX
Definition at line 79 of file DDCMotorWheels.h.
Referenced by attach(), DDCMotorWheels(), detach(), DXGetPwm(), GetBalancingFw(), GetBalancingRev(), ResetBalancing(), ResetBalancingFw(), ResetBalancingRev(), SetBalancingFw(), SetBalancingRev(), SetStepValue(), SXBrake(), SXGetPwm(), SXIsRunning(), SXSetVel(), and ~DDCMotorWheels().
The documentation for this class was generated from the following files:
src/_ddcmotorwheels/DDCMotorWheels.h
src/_ddcmotorwheels/DDCMotorWheels.cpp