My Project: DGpioChip Class Reference
DGpioChip Class Reference
#include <dgpiochip.h>
Public Member Functions
DGpioChip (int deviceIndex)
~DGpioChip ()
DGpioHandle handle (void)
std::string getLastError (void)
bool isReady (void)
std::string getInfo ()
Private Attributes
DGpioHandle gpioChipHandle
lgChipInfo_t cInfo
Detailed Description
Definition at line 9 of file dgpiochip.h.
Constructor & Destructor Documentation
DGpioChip()
DGpioChip::DGpioChip (int deviceIndex)
Definition at line 5 of file dgpiochip.cpp.
References cInfo, and gpioChipHandle.
~DGpioChip()
DGpioChip::~DGpioChip ()
Definition at line 16 of file dgpiochip.cpp.
References gpioChipHandle.
Member Function Documentation
getInfo()
std::string DGpioChip::getInfo (void)
Definition at line 43 of file dgpiochip.cpp.
References cInfo, and gpioChipHandle.
Referenced by main().
getLastError()
std::string DGpioChip::getLastError (void)
Definition at line 28 of file dgpiochip.cpp.
References getErrorCode(), and gpioChipHandle.
Referenced by main().
handle()
DGpioHandle DGpioChip::handle (void)
Definition at line 23 of file dgpiochip.cpp.
References gpioChipHandle.
Referenced by main().
isReady()
bool DGpioChip::isReady (void)
Definition at line 38 of file dgpiochip.cpp.
References gpioChipHandle.
Referenced by main().
Member Data Documentation
cInfo
lgChipInfo_t DGpioChip::cInfo private
Definition at line 21 of file dgpiochip.h.
Referenced by DGpioChip(), and getInfo().
gpioChipHandle
DGpioHandle DGpioChip::gpioChipHandle private
Definition at line 20 of file dgpiochip.h.
Referenced by DGpioChip(), getInfo(), getLastError(), handle(), isReady(), and ~DGpioChip().
The documentation for this class was generated from the following files:
src/dgpio/dgpiochip.h
src/dgpio/dgpiochip.cpp