My Project: DMPacket Class Reference
DMPacket Class Reference
#include <dmpacket.h>
Public Member Functions
DMPacket ()
Crea un pacchetto vuoto.
DMPacket (uint8_t Buff[], uint16_t BuffLen)
Crea un pacchetto eseguendo il parsing del buffer passato.
DMPacket (const std::vector< uint8_t > &BuffVec)
Crea un pacchetto eseguendo il parsing del buffer passato.
~DMPacket ()
Distruttore.
void Clear ()
Resetta il pacchetto.
uint8_t Size (void)
uint8_t * BufferRaw (void)
Non usare per inserire dati.
std::vector< uint8_t > & Buffer (void)
void SetBuffer (const uint8_t Buff[], uint16_t BuffLen)
Copia Buff direttamente nel buffer del pacchetto.
void SetBuffer (const char Buff[], uint16_t BuffLen)
void SetBuffer (const std::vector< uint8_t > &BuffVec)
Copia BuffVect direttamente nel buffer del pacchetto.
uint8_t ReadByte (uint16_t Offset)
Read a byte from data payload.
uint16_t ReadWord (uint16_t Offset)
Read a word from data payload.
uint32_t ReadDWord (uint16_t Offset)
Read a double-word from data payload.
int8_t ReadInt8 (uint16_t Offset)
Read a 8 bit signed integer from data payload.
int16_t ReadInt16 (uint16_t Offset)
Read a 16 bit signed integer from data payload.
float ReadFloat (uint16_t Offset)
Read a 32 bit float from data.
std::vector< uint8_t > ReadBytes (uint16_t Offset, uint16_t Count=0)
Legge i dati del pacchetto e li mette in un vettore di bytes (uint8_t)
uint16_t ReadBytes (std::vector< uint8_t > &Dest, uint16_t Offset, uint16_t Count=0)
Legge i dati del pacchetto e li mette in un vettore di bytes (uint8_t)
std::vector< uint16_t > ReadWords (uint16_t Offset, uint16_t Count=0)
Legge i dati del pacchetto e li mette in un vettore di words (uint16_t)
std::vector< uint32_t > ReadDWords (uint16_t Offset, uint16_t Count=0)
Legge i dati del pacchetto e li mette in un vettore di double words (uint32_t)
std::string ReadString (uint16_t Offset=0, uint16_t Lenght=0)
void PushByte (uint8_t Byte)
Add a single byte to the packet.
void PushWord (uint16_t Word)
Add a WORD (2 bytes) to the packet.
void PushDWord (uint32_t DWord)
Add a DWORD (4 bytes) to the packet.
void PushInt16 (int16_t Int)
Add a 16 bit integer value to the packet.
void PushFloat (float Float)
Add a 32 bit floating point value to the packet.
void PushData (const std::vector< uint8_t > &BuffVec)
void pushData (const uint8_t buff[], const uint16_t buffSize)
void PushString (std::string Str)
Add a string as a sequence of bytes to the packet.
uint8_t ShiftByte (void)
Pop a byte from begin of the buffer.
std::string ShiftString (uint16_t Lenght=0)
std::string ToHexString (uint16_t Offset=0)
std::string ToAsciiString (uint16_t Offset=0)
Private Attributes
std::vector< uint8_t > PacketBuff
uint16_t ShiftIndex
Detailed Description
Definition at line 17 of file dmpacket.h.
Constructor & Destructor Documentation
DMPacket() [1/3]
DMPacket::DMPacket ()
Crea un pacchetto vuoto.
Definition at line 45 of file dmpacket.cpp.
References Clear().
DMPacket() [2/3]
DMPacket::DMPacket (uint8_t Buff[], uint16_t BuffLen)
Crea un pacchetto eseguendo il parsing del buffer passato.
Parameters
BuffVec -> un std::vector<uint8_t>.
Definition at line 61 of file dmpacket.cpp.
References SetBuffer().
DMPacket() [3/3]
DMPacket::DMPacket (const std::vector< uint8_t > & BuffVec)
Crea un pacchetto eseguendo il parsing del buffer passato.
Parameters
Buff -> buffer di bytes.
Definition at line 53 of file dmpacket.cpp.
References SetBuffer().
~DMPacket()
DMPacket::~DMPacket ()
Distruttore.
Definition at line 66 of file dmpacket.cpp.
Member Function Documentation
Buffer()
std::vector< uint8_t > & DMPacket::Buffer (void)
Returns
Il riferimeto al buffer totale del pacchetto come vector.
Definition at line 132 of file dmpacket.cpp.
References PacketBuff.
BufferRaw()
uint8_t * DMPacket::BufferRaw (void)
Non usare per inserire dati.
Returns
un puntatore all'intero buffer del pacchetto.
uint8_t*
Definition at line 127 of file dmpacket.cpp.
References PacketBuff.
Clear()
void DMPacket::Clear ()
Resetta il pacchetto.
-Riporta la dimensione a HDR_SIZE. -Azzera il contenuto. -Azzera li ShiftIndex
Definition at line 75 of file dmpacket.cpp.
References PacketBuff, and ShiftIndex.
Referenced by DMPacket().
PushByte()
void DMPacket::PushByte (uint8_t Byte)
Add a single byte to the packet.
N.B. DataType in header is not changed.
Parameters
Byte -> byte to add.
Definition at line 443 of file dmpacket.cpp.
References PacketBuff.
PushData()
void DMPacket::PushData (const std::vector< uint8_t > & BuffVec)
Definition at line 542 of file dmpacket.cpp.
References PacketBuff.
pushData()
void DMPacket::pushData (const uint8_t buff[], const uint16_t buffSize)
Definition at line 554 of file dmpacket.cpp.
References PacketBuff.
PushDWord()
void DMPacket::PushDWord (uint32_t DWord)
Add a DWORD (4 bytes) to the packet.
N.B. DataType in header is not changed.
Parameters
DWord -> DWORD to add.
Definition at line 468 of file dmpacket.cpp.
References HIBYTE, HIWORD, LOBYTE, LOWORD, and PacketBuff.
PushFloat()
void DMPacket::PushFloat (float Float)
Add a 32 bit floating point value to the packet.
N.B. DataType in header is not changed.
Parameters
Float -> 32 bit float to add.
Definition at line 495 of file dmpacket.cpp.
References HIBYTE, HIWORD, LOBYTE, LOWORD, and PacketBuff.
PushInt16()
void DMPacket::PushInt16 (int16_t Int16)
Add a 16 bit integer value to the packet.
N.B. DataType in header is not changed.
Parameters
Int16
Definition at line 484 of file dmpacket.cpp.
References PushWord().
PushString()
void DMPacket::PushString (std::string Str)
Add a string as a sequence of bytes to the packet.
N.B. DataType in header is not changed.
Parameters
Str -> string to add.
Definition at line 519 of file dmpacket.cpp.
References PacketBuff.
PushWord()
void DMPacket::PushWord (uint16_t Word)
Add a WORD (2 bytes) to the packet.
N.B. DataType in header is not changed.
Parameters
Word -> WORD to add.
Definition at line 454 of file dmpacket.cpp.
References HIBYTE, LOBYTE, and PacketBuff.
Referenced by PushInt16().
ReadByte()
uint8_t DMPacket::ReadByte (uint16_t Offset)
Read a byte from data payload.
Parameters
Index -> Offset of byte to read in the payload.
Returns
8 bit value.
Definition at line 346 of file dmpacket.cpp.
References PacketBuff.
Referenced by ReadInt8().
ReadBytes() [1/2]
uint16_t DMPacket::ReadBytes (std::vector< uint8_t > & Dest, uint16_t Offset, uint16_t Count = 0)
Legge i dati del pacchetto e li mette in un vettore di bytes (uint8_t)
Parameters
DataDest -> Vettore di bytes in cui mettere i dati
Returns
false se i dati del pacchetto non sono di tipo byte o se è un pacchetto senza senza dati.
Definition at line 209 of file dmpacket.cpp.
References PacketBuff.
ReadBytes() [2/2]
std::vector< uint8_t > DMPacket::ReadBytes (uint16_t Offset, uint16_t Count = 0)
Legge i dati del pacchetto e li mette in un vettore di bytes (uint8_t)
Returns
un vector<uint8_t> contenente il payload
Definition at line 171 of file dmpacket.cpp.
References PacketBuff.
ReadDWord()
uint32_t DMPacket::ReadDWord (uint16_t Offset)
Read a double-word from data payload.
Parameters
Index -> Offset of byte in the payload where to start reading.
Returns
32 bit value.
Definition at line 386 of file dmpacket.cpp.
References DWORD_B, and PacketBuff.
Referenced by main(), and ReadFloat().
ReadDWords()
std::vector< uint32_t > DMPacket::ReadDWords (uint16_t Offset, uint16_t Count = 0)
Legge i dati del pacchetto e li mette in un vettore di double words (uint32_t)
Parameters
Data -> Vettore di words in cui mettere i dati
Returns
false se i dati del pacchetto non sono di tipo byte o se è un pacchetto senza senza dati.
Definition at line 281 of file dmpacket.cpp.
References DWORD_B, and PacketBuff.
ReadFloat()
float DMPacket::ReadFloat (uint16_t Offset)
Read a 32 bit float from data.
Parameters
Index -> Number of the float to read (first is 1).
Returns
float value.
Definition at line 423 of file dmpacket.cpp.
References ReadDWord().
Referenced by main().
ReadInt16()
int16_t DMPacket::ReadInt16 (uint16_t Offset)
Read a 16 bit signed integer from data payload.
Parameters
Index -> Offset of byte to read in the payload.
Returns
16 bit integer value.
Definition at line 403 of file dmpacket.cpp.
References ReadWord().
Referenced by main().
ReadInt8()
int8_t DMPacket::ReadInt8 (uint16_t Offset)
Read a 8 bit signed integer from data payload.
Parameters
Index -> Offset of byte to read in the payload.
Returns
integer value.
Definition at line 413 of file dmpacket.cpp.
References ReadByte().
ReadString()
std::string DMPacket::ReadString (uint16_t Offset = 0, uint16_t Lenght = 0)
Parameters
Offset
Len
Returns
std::string
Definition at line 143 of file dmpacket.cpp.
References PacketBuff.
Referenced by ShiftString().
ReadWord()
uint16_t DMPacket::ReadWord (uint16_t Offset)
Read a word from data payload.
Parameters
Index -> Offset of byte in the payload where to start reading.
Returns
16 bit value.
Definition at line 369 of file dmpacket.cpp.
References PacketBuff, and WORD.
Referenced by main(), and ReadInt16().
ReadWords()
std::vector< uint16_t > DMPacket::ReadWords (uint16_t Offset, uint16_t Count = 0)
Legge i dati del pacchetto e li mette in un vettore di words (uint16_t)
Parameters
Data -> Vettore di words in cui mettere i dati
Returns
false se i dati del pacchetto non sono di tipo byte o se è un pacchetto senza senza dati.
Definition at line 243 of file dmpacket.cpp.
References PacketBuff.
SetBuffer() [1/3]
void DMPacket::SetBuffer (const char Buff[], uint16_t BuffLen)
Definition at line 105 of file dmpacket.cpp.
References SetBuffer().
SetBuffer() [2/3]
void DMPacket::SetBuffer (const std::vector< uint8_t > & BuffVec)
Copia BuffVect direttamente nel buffer del pacchetto.
Parameters
BuffVec -> un std::vector<uint8_t>.
Returns
true
false
Definition at line 116 of file dmpacket.cpp.
References PacketBuff, and ShiftIndex.
SetBuffer() [3/3]
void DMPacket::SetBuffer (const uint8_t Buff[], uint16_t BuffSize)
Copia Buff direttamente nel buffer del pacchetto.
Parameters
Buff -> buffer di bytes.
BuffSize -> lunghezza del buffer (max 256).
Definition at line 93 of file dmpacket.cpp.
References PacketBuff, and ShiftIndex.
Referenced by DMPacket(), and SetBuffer().
ShiftByte()
uint8_t DMPacket::ShiftByte (void)
Pop a byte from begin of the buffer.
It does not really shift the buffer, use a shift index to set the current pop posision (shifting a vector can be an expensive operation on vector).
Returns
uint8_t
Definition at line 569 of file dmpacket.cpp.
References PacketBuff, and ShiftIndex.
ShiftString()
std::string DMPacket::ShiftString (uint16_t Lenght = 0)
Definition at line 579 of file dmpacket.cpp.
References PacketBuff, ReadString(), and ShiftIndex.
Size()
uint8_t DMPacket::Size (void)
Returns
la lunghezza in bytes del paccketto
Definition at line 82 of file dmpacket.cpp.
References PacketBuff.
Referenced by Send().
ToAsciiString()
std::string DMPacket::ToAsciiString (uint16_t Offset = 0)
Definition at line 327 of file dmpacket.cpp.
References PacketBuff.
ToHexString()
std::string DMPacket::ToHexString (uint16_t Offset = 0)
Definition at line 313 of file dmpacket.cpp.
References PacketBuff.
Member Data Documentation
PacketBuff
std::vector<uint8_t> DMPacket::PacketBuff private
Definition at line 19 of file dmpacket.h.
Referenced by Buffer(), BufferRaw(), Clear(), PushByte(), PushData(), pushData(), PushDWord(), PushFloat(), PushString(), PushWord(), ReadByte(), ReadBytes(), ReadDWord(), ReadDWords(), ReadString(), ReadWord(), ReadWords(), SetBuffer(), ShiftByte(), ShiftString(), Size(), ToAsciiString(), and ToHexString().
ShiftIndex
uint16_t DMPacket::ShiftIndex private
Definition at line 20 of file dmpacket.h.
Referenced by Clear(), SetBuffer(), ShiftByte(), and ShiftString().
The documentation for this class was generated from the following files:
src/dmpacket/dmpacket.h
src/dmpacket/dmpacket.cpp