My Project: DServo Class Reference
DServo Class Reference
#include <dservo.h>
Public Member Functions
void detach (void)
Unset servo pin as pwm (Arduino api compatibility)
bool attached (void)
Check if servo pin is configurated as pwm (Arduino api compatibility)
void write (short int degrees)
Set servo position in Degrees from 0 to 180 where 90 is the centre position (Arduino api compatibility)
void writeMicroseconds (int us)
Set servo position in micro seconds from 1000 to 2000 where 1500 is centre position (Arduino api compatibility)
short int read (void)
Read the current angle of the servo, that is the value passed to the last call to write() (Arduino api compatibility)
DServo (int pin, DGpioHandle gpioHandle=-1)
Constructor 2.
~DServo ()
Destructor.
void begin (void)
Init servo pina as pwm.
void writeRange (float pos)
Set servo position in range from 0.0 to 1.0 where 0.05 is centre position.
void writeDegrees (short int degrees)
Wrapper for write()
void fullCCW (void)
Move servo fully counterclockwise position MaxPulseUs (180 degrees).
void fullCW (void)
Move servo fully clockwise position MinPulseUs (0 degrees).
void center (void)
Move servo to middle position between MaxPulseUs and MinPulseUs (90 degrees).
void home (void)
Move servo to home position CurrHomeUs.
void stepCCWDegrees (short int degreeStep)
Move servo counterclockwise by custom degrees.
void stepCWDegrees (short int degreeStep)
Move servo clockwise by custom degrees.
void stepCCWUs (int us)
Move servo counterclockwise by custom pulse-width.
void stepCWUs (int us)
Move servo clockwise by custom pulse-width.
void stepCCW (void)
Move servo counterclockwise by CurrStepUs pulse-width.
void stepCW (void)
Move servo clockwise by CurrStepUs pulse-width.
void setMinPulseUs (int us)
Set minimum pulse-witdh that can be set.
void setMaxPulseUs (int us)
Set maximum pulse-width that can be set.
int getMaxPulseUs (void)
Get current maximum pulse-width that can be set.
int getMinPulseUs (void)
Get current minimum pulse-width that can be set.
short int getCurrDegrees (void)
Get current Degrees set.
int getCurrPulseUs (void)
Get current pulse-width set.
void setStepDegrees (short int degrees)
Set degrees value to use in step moving functions.
short int getStepDegrees (void)
Get current degrees value used in step moving functions.
void setStepUs (int Us)
Set pulse-width value to use in step moving functions.
int getStepUs (void)
Get current pulse-width value used in step moving functions.
void setHomeDegrees (short int degrees)
Set degrees value used for home position.
short int getHomeDegrees (void)
Get current pulse-width used for home position.
void setHomeUs (int Us)
Set pulse-width used for home position.
int getHomeUs (void)
Get current pulse-width used for home position.
int resetMinPulseValue (void)
Reset minimum pulse-width to default DEFAULT_MIN_PULSE_US.
int resetMaxPulseValue (void)
Reset maxinum pulse-width to default DEFAULT_MAX_PULSE_US.
int resetStepValue (void)
Reset step pulse-width to default DEFAULT_STEP_VALUE.
int resetHomeValue (void)
Reset pulse-width to default: (DEFAULT_MAX_PULSE_US-DEFAULT_MIN_PULSE_US)/2.
void setDefaultValues (bool outServo)
Set all params to default values.
int degreesToUs (short int degrees)
Convert degrees value to pulse-width Us for this servo.
short int usToDegrees (int us)
Convert Us pulse-width value degrees for this servo.
short int getPin (void)
Get attached pin number.
std::string getLastError (void)
Static Public Attributes
static const unsigned int DEFAULT_MIN_PULSE_US =1000
Constants.
static const unsigned int DEFAULT_MAX_PULSE_US =2000
Private Member Functions
void servoOut ()
TODO: Shorthand for the write and read functions.
Private Attributes
DPwmOut * dPwmOut
Output pwm signal to servo pin.
int pin
int currPulseUs
short int currDegrees
Current pulse-width in us.
int minPulseUs
Current servo position in degrees from 0 to 180 where 90 is centre position.
int maxPulseUs
Pulse-width that sets servo to fully counter-clockwise position.
short int currStepDegrees
Pulse-width that sets servo to fully clockwise position.
int currStepUs
Current degrees value used for step.
int currHomeUs
Current pulse-width value used for step.
DGpioHandle handle
Current pulse-width value used for home position.
Detailed Description
Definition at line 7 of file dservo.h.
Constructor & Destructor Documentation
DServo()
DServo::DServo (int gpioPin, DGpioHandle gpioHandle = -1)
Constructor 2.
Construct a new DServo::DServo object and attach to pin.
Parameters
pin -> Pwm output pin
Definition at line 12 of file dservo.cpp.
References dPwmOut, handle, pin, and setDefaultValues().
~DServo()
DServo::~DServo ()
Destructor.
Definition at line 20 of file dservo.cpp.
References detach().
Member Function Documentation
attached()
bool DServo::attached (void)
Check if servo pin is configurated as pwm (Arduino api compatibility)
Returns
@Attached value
Definition at line 74 of file dservo.cpp.
References dPwmOut, and DPwmOut::isReady().
Referenced by ServoRunTest().
begin()
void DServo::begin (void)
Init servo pina as pwm.
Parameters
Pin -> Servo attached pin nr
Definition at line 45 of file dservo.cpp.
References DPwmOut::begin(), dPwmOut, handle, DPwmOut::on(), pin, and DPwmOut::setMicros().
Referenced by main().
center()
void DServo::center (void)
Move servo to middle position between MaxPulseUs and MinPulseUs (90 degrees).
Definition at line 154 of file dservo.cpp.
References write().
degreesToUs()
int DServo::degreesToUs (short int degrees)
Convert degrees value to pulse-width Us for this servo.
Definition at line 357 of file dservo.cpp.
References currDegrees, mapValue, maxPulseUs, and minPulseUs.
Referenced by setDefaultValues(), setHomeDegrees(), setStepDegrees(), write(), and writeRange().
detach()
void DServo::detach (void)
Unset servo pin as pwm (Arduino api compatibility)
Reset servo pin to output mode and set it to LOW.
Definition at line 61 of file dservo.cpp.
References currPulseUs, dPwmOut, and servoOut().
Referenced by DCMotorRunTest(), ServoRunTest(), and ~DServo().
fullCCW()
void DServo::fullCCW (void)
Move servo fully counterclockwise position MaxPulseUs (180 degrees).
Definition at line 144 of file dservo.cpp.
References write().
fullCW()
void DServo::fullCW (void)
Move servo fully clockwise position MinPulseUs (0 degrees).
Definition at line 149 of file dservo.cpp.
References write().
getCurrDegrees()
short int DServo::getCurrDegrees (void)
Get current Degrees set.
Definition at line 225 of file dservo.cpp.
References currDegrees.
getCurrPulseUs()
int DServo::getCurrPulseUs (void)
Get current pulse-width set.
Definition at line 230 of file dservo.cpp.
References currPulseUs.
Referenced by main().
getHomeDegrees()
short int DServo::getHomeDegrees (void)
Get current pulse-width used for home position.
Definition at line 282 of file dservo.cpp.
References currHomeUs, and usToDegrees().
getHomeUs()
int DServo::getHomeUs (void)
Get current pulse-width used for home position.
Definition at line 292 of file dservo.cpp.
References currHomeUs.
getLastError()
std::string DServo::getLastError (void)
Definition at line 372 of file dservo.cpp.
References DERR_CLASS_NOT_BEGUN, dPwmOut, getErrorCode(), and DPwmOut::getLastError().
getMaxPulseUs()
int DServo::getMaxPulseUs (void)
Get current maximum pulse-width that can be set.
Definition at line 215 of file dservo.cpp.
References maxPulseUs.
getMinPulseUs()
int DServo::getMinPulseUs (void)
Get current minimum pulse-width that can be set.
Definition at line 220 of file dservo.cpp.
References minPulseUs.
getPin()
short int DServo::getPin (void)
Get attached pin number.
Definition at line 367 of file dservo.cpp.
References dPwmOut, and DPwmOut::getPin().
getStepDegrees()
short int DServo::getStepDegrees (void)
Get current degrees value used in step moving functions.
Definition at line 251 of file dservo.cpp.
References currStepDegrees.
getStepUs()
int DServo::getStepUs (void)
Get current pulse-width value used in step moving functions.
Definition at line 272 of file dservo.cpp.
References currStepUs.
home()
void DServo::home (void)
Move servo to home position CurrHomeUs.
Home position is an arbitrary value that can be set using SetHomePositionUs() or SetHomePositionDegree()
Definition at line 162 of file dservo.cpp.
References currHomeUs, and writeMicroseconds().
read()
short int DServo::read (void)
Read the current angle of the servo, that is the value passed to the last call to write() (Arduino api compatibility)
Returns
current servo position in degrees from 0 to 180
Definition at line 116 of file dservo.cpp.
References currDegrees.
Referenced by PrintMenu().
resetHomeValue()
int DServo::resetHomeValue (void)
Reset pulse-width to default: (DEFAULT_MAX_PULSE_US-DEFAULT_MIN_PULSE_US)/2.
Servo will not be re-positioned.
Returns
int New current home pulse-width in us.
Definition at line 344 of file dservo.cpp.
References currHomeUs, maxPulseUs, and minPulseUs.
Referenced by setDefaultValues().
resetMaxPulseValue()
int DServo::resetMaxPulseValue (void)
Reset maxinum pulse-width to default DEFAULT_MAX_PULSE_US.
Servo will be re-positioned.
Returns
int New current maxinum pulse-width in us.
Definition at line 318 of file dservo.cpp.
References currDegrees, currPulseUs, DEFAULT_MAX_PULSE_US, maxPulseUs, and write().
resetMinPulseValue()
int DServo::resetMinPulseValue (void)
Reset minimum pulse-width to default DEFAULT_MIN_PULSE_US.
Servo will be re-positioned.
Returns
int New current mininum pulse-width in us.
Definition at line 302 of file dservo.cpp.
References currDegrees, currPulseUs, DEFAULT_MIN_PULSE_US, minPulseUs, and write().
resetStepValue()
int DServo::resetStepValue (void)
Reset step pulse-width to default DEFAULT_STEP_VALUE.
Returns
int New current step pulse-width in us.
Definition at line 332 of file dservo.cpp.
References currStepDegrees, currStepUs, DEFAULT_STEP_US, and usToDegrees().
Referenced by setDefaultValues().
servoOut()
void DServo::servoOut (void) private
TODO: Shorthand for the write and read functions.
Definition at line 350 of file dservo.cpp.
References currPulseUs, dPwmOut, and DPwmOut::setMicros().
Referenced by detach(), setDefaultValues(), write(), writeMicroseconds(), and writeRange().
setDefaultValues()
void DServo::setDefaultValues (bool outServo)
Set all params to default values.
N.B.
Only values are chaged (no servo re-positioning)
Definition at line 28 of file dservo.cpp.
References currDegrees, currPulseUs, DEFAULT_MAX_PULSE_US, DEFAULT_MIN_PULSE_US, degreesToUs(), maxPulseUs, minPulseUs, resetHomeValue(), resetStepValue(), and servoOut().
Referenced by DServo().
setHomeDegrees()
void DServo::setHomeDegrees (short int degrees)
Set degrees value used for home position.
Definition at line 277 of file dservo.cpp.
References currHomeUs, and degreesToUs().
setHomeUs()
void DServo::setHomeUs (int Us)
Set pulse-width used for home position.
Definition at line 287 of file dservo.cpp.
References currHomeUs.
setMaxPulseUs()
void DServo::setMaxPulseUs (int us)
Set maximum pulse-width that can be set.
Definition at line 206 of file dservo.cpp.
References currPulseUs, maxPulseUs, and writeMicroseconds().
setMinPulseUs()
void DServo::setMinPulseUs (int us)
Set minimum pulse-witdh that can be set.
Definition at line 197 of file dservo.cpp.
References currPulseUs, minPulseUs, and writeMicroseconds().
setStepDegrees()
void DServo::setStepDegrees (short int degrees)
Set degrees value to use in step moving functions.
Parameters
Value -> step value from 1 to DDCMW_MAX_VEL
Definition at line 238 of file dservo.cpp.
References currStepDegrees, currStepUs, degreesToUs(), and MAX_STEP_DEGREES.
setStepUs()
void DServo::setStepUs (int us)
Set pulse-width value to use in step moving functions.
Parameters
Value -> step value from 1 to DDCMW_MAX_VEL
Definition at line 259 of file dservo.cpp.
References currStepDegrees, currStepUs, MAX_STEP_US, and usToDegrees().
stepCCW()
void DServo::stepCCW (void)
Move servo counterclockwise by CurrStepUs pulse-width.
Definition at line 177 of file dservo.cpp.
References currStepUs, and stepCCWUs().
stepCCWDegrees()
void DServo::stepCCWDegrees (short int degreeStep)
Move servo counterclockwise by custom degrees.
Definition at line 167 of file dservo.cpp.
References currDegrees, and write().
stepCCWUs()
void DServo::stepCCWUs (int us)
Move servo counterclockwise by custom pulse-width.
Definition at line 187 of file dservo.cpp.
References currPulseUs, and writeMicroseconds().
Referenced by stepCCW().
stepCW()
void DServo::stepCW (void)
Move servo clockwise by CurrStepUs pulse-width.
Definition at line 182 of file dservo.cpp.
References currStepUs, and stepCWUs().
stepCWDegrees()
void DServo::stepCWDegrees (short int degreeStep)
Move servo clockwise by custom degrees.
Definition at line 172 of file dservo.cpp.
References currDegrees, and write().
stepCWUs()
void DServo::stepCWUs (int us)
Move servo clockwise by custom pulse-width.
Definition at line 192 of file dservo.cpp.
References currPulseUs, and writeMicroseconds().
Referenced by stepCW().
usToDegrees()
short int DServo::usToDegrees (int us)
Convert Us pulse-width value degrees for this servo.
Definition at line 362 of file dservo.cpp.
References mapValue, maxPulseUs, and minPulseUs.
Referenced by getHomeDegrees(), resetStepValue(), setStepUs(), and writeMicroseconds().
write()
void DServo::write (short int degrees)
Set servo position in Degrees from 0 to 180 where 90 is the centre position (Arduino api compatibility)
Parameters
Degrees-> Degrees value from 0 to 180
Definition at line 82 of file dservo.cpp.
References currDegrees, currPulseUs, degreesToUs(), and servoOut().
Referenced by center(), fullCCW(), fullCW(), resetMaxPulseValue(), resetMinPulseValue(), stepCCWDegrees(), stepCWDegrees(), and writeDegrees().
writeDegrees()
void DServo::writeDegrees (short int degrees)
Wrapper for write()
Parameters
Degrees-> Degrees value from 0 to 180
Definition at line 139 of file dservo.cpp.
References write().
writeMicroseconds()
void DServo::writeMicroseconds (int us)
Set servo position in micro seconds from 1000 to 2000 where 1500 is centre position (Arduino api compatibility)
Parameters
Us -> Micro seconds value. It can be a value from 500 to 2500 but the reaction depends on servo motor.
Definition at line 97 of file dservo.cpp.
References currDegrees, currPulseUs, maxPulseUs, minPulseUs, servoOut(), and usToDegrees().
Referenced by home(), loop(), main(), ServoRunTest(), setMaxPulseUs(), setMinPulseUs(), stepCCWUs(), and stepCWUs().
writeRange()
void DServo::writeRange (float Pos)
Set servo position in range from 0.0 to 1.0 where 0.05 is centre position.
Parameters
Pos -> position from 0.0 to 1.0 where 0.5 is centre position
Definition at line 124 of file dservo.cpp.
References currDegrees, currPulseUs, degreesToUs(), and servoOut().
Member Data Documentation
currDegrees
short int DServo::currDegrees private
Current pulse-width in us.
Definition at line 135 of file dservo.h.
Referenced by degreesToUs(), getCurrDegrees(), read(), resetMaxPulseValue(), resetMinPulseValue(), setDefaultValues(), stepCCWDegrees(), stepCWDegrees(), write(), writeMicroseconds(), and writeRange().
currHomeUs
int DServo::currHomeUs private
Current pulse-width value used for step.
Definition at line 140 of file dservo.h.
Referenced by getHomeDegrees(), getHomeUs(), home(), resetHomeValue(), setHomeDegrees(), and setHomeUs().
currPulseUs
int DServo::currPulseUs private
Definition at line 134 of file dservo.h.
Referenced by detach(), getCurrPulseUs(), resetMaxPulseValue(), resetMinPulseValue(), servoOut(), setDefaultValues(), setMaxPulseUs(), setMinPulseUs(), stepCCWUs(), stepCWUs(), write(), writeMicroseconds(), and writeRange().
currStepDegrees
short int DServo::currStepDegrees private
Pulse-width that sets servo to fully clockwise position.
Definition at line 138 of file dservo.h.
Referenced by getStepDegrees(), resetStepValue(), setStepDegrees(), and setStepUs().
currStepUs
int DServo::currStepUs private
Current degrees value used for step.
Definition at line 139 of file dservo.h.
Referenced by getStepUs(), resetStepValue(), setStepDegrees(), setStepUs(), stepCCW(), and stepCW().
DEFAULT_MAX_PULSE_US
const unsigned int DServo::DEFAULT_MAX_PULSE_US =2000 static
Definition at line 11 of file dservo.h.
Referenced by resetMaxPulseValue(), and setDefaultValues().
DEFAULT_MIN_PULSE_US
const unsigned int DServo::DEFAULT_MIN_PULSE_US =1000 static
Constants.
Definition at line 10 of file dservo.h.
Referenced by resetMinPulseValue(), and setDefaultValues().
dPwmOut
DPwmOut* DServo::dPwmOut private
Output pwm signal to servo pin.
Definition at line 131 of file dservo.h.
Referenced by attached(), begin(), detach(), DServo(), getLastError(), getPin(), and servoOut().
handle
DGpioHandle DServo::handle private
Current pulse-width value used for home position.
Definition at line 142 of file dservo.h.
Referenced by begin(), and DServo().
maxPulseUs
int DServo::maxPulseUs private
Pulse-width that sets servo to fully counter-clockwise position.
Definition at line 137 of file dservo.h.
Referenced by degreesToUs(), getMaxPulseUs(), resetHomeValue(), resetMaxPulseValue(), setDefaultValues(), setMaxPulseUs(), usToDegrees(), and writeMicroseconds().
minPulseUs
int DServo::minPulseUs private
Current servo position in degrees from 0 to 180 where 90 is centre position.
Definition at line 136 of file dservo.h.
Referenced by degreesToUs(), getMinPulseUs(), resetHomeValue(), resetMinPulseValue(), setDefaultValues(), setMinPulseUs(), usToDegrees(), and writeMicroseconds().
pin
int DServo::pin private
Definition at line 132 of file dservo.h.
Referenced by begin(), and DServo().
The documentation for this class was generated from the following files:
src/dservo/dservo.h
src/dservo/dservo.cpp