My Project: INA226 Class Reference
INA226 Class Reference
#include <INA226.h>
Public Member Functions
INA226 (uint8_t deviceAddr, DI2CBusHandle i2cBusHandle)
~INA226 ()
bool begin (void)
float voltage (void)
float current (void)
float power (void)
std::string getInfo (void)
Public Member Functions inherited from DI2CMaster
DI2CMaster (DI2CBusHandle i2cBusHandle, uint16_t i2cMaxBufferLenght=0)
Construct a new DI2CMaster::DI2CMaster object.
~DI2CMaster ()
bool isReady (void)
std::string getLastError (void)
bool writeByte (uint8_t slaveAddr, uint8_t cmdReg, uint8_t data)
Write a BYTE at specified i2c register of the slave device.
bool writeWord (uint8_t slaveAddr, uint8_t cmdReg, uint16_t data)
Write a WORD (2 bytes) at specified i2c register of the slave device.
bool writeBuf (uint8_t slaveAddr, uint8_t cmdReg, uint8_t *writeBuffer, uint16_t writeLen)
Write a BUFFER at specified i2c register of the slave device.
uint8_t recvByte (uint8_t slaveAddr)
Read a BYTE from an i2c slave device.
uint16_t recvWord (uint8_t slaveAddr)
Read a WORD(2 bytes) from an i2c slave device.
bool recvBuf (uint8_t slaveAddr, uint8_t *recvBuf, uint16_t recvLen)
Read a BUFFER from an i2c slave device.
uint8_t askForByte (uint8_t slaveAddr, uint8_t cmdReg)
Read a BYTE from specified i2c register of the slave device.
uint16_t askForWord (uint8_t slaveAddr, uint8_t cmdReg)
Read a WORD from specified i2c register of the slave device.
bool askForBuf (uint8_t slaveAddr, uint8_t cmdReg, uint8_t *recvBuf, uint16_t recvLen)
Read a BUFFER from specified i2c register of the slave device.
bool sendByte (uint8_t slaveAddr, uint8_t data)
Send a BYTE to a slave device.
bool sendWord (uint8_t slaveAddr, uint16_t data)
Send a WORD (2 bytes) to a slave device.
bool sendBuf (uint8_t slaveAddr, uint8_t *data, uint16_t dataLen)
Send a BUFFER to a slave device.
Private Attributes
uint8_t devAddr
Detailed Description
Definition at line 40 of file INA226.h.
Constructor & Destructor Documentation
INA226()
INA226::INA226 (uint8_t deviceAddr, DI2CBusHandle i2cBusHandle)
Definition at line 25 of file INA226.cpp.
References devAddr.
~INA226()
INA226::~INA226 ()
Definition at line 30 of file INA226.cpp.
Member Function Documentation
begin()
bool INA226::begin (void)
Definition at line 35 of file INA226.cpp.
References devAddr, INA226_CAL_REG, INA226_CFG_REG, and DI2CMaster::writeWord().
Referenced by main().
current()
float INA226::current (void)
Definition at line 56 of file INA226.cpp.
References DI2CMaster::askForWord(), devAddr, and INA226_CURRENT_REG.
Referenced by main().
getInfo()
std::string INA226::getInfo (void)
Definition at line 82 of file INA226.cpp.
References DI2CMaster::askForWord(), devAddr, INA226_CFG_REG, INA226_DIE_ID, and INA226_MANUFACTURER_ID.
Referenced by main().
power()
float INA226::power (void)
Definition at line 69 of file INA226.cpp.
References DI2CMaster::askForWord(), devAddr, and INA226_POWER_REG.
Referenced by main().
voltage()
float INA226::voltage (void)
Definition at line 43 of file INA226.cpp.
References DI2CMaster::askForWord(), devAddr, and INA226_BUS_VOLT_REG.
Referenced by main().
Member Data Documentation
devAddr
uint8_t INA226::devAddr private
Definition at line 52 of file INA226.h.
Referenced by begin(), current(), getInfo(), INA226(), power(), and voltage().
The documentation for this class was generated from the following files:
drivers/INA226/INA226.h
drivers/INA226/INA226.cpp