My Project: INA228 Class Reference
INA228 Class Reference
#include <INA228.h>
Public Member Functions
INA228 (uint8_t deviceAddr, DI2CBusHandle i2cBusHandle)
~INA228 ()
bool begin (void)
float voltage (void)
float dietemp (void)
float shuntvoltage (void)
float current (void)
float power (void)
float energy (void)
float charge (void)
std::string getInfo (void)
Public Member Functions inherited from DI2CMaster
DI2CMaster (DI2CBusHandle i2cBusHandle, uint16_t i2cMaxBufferLenght=0)
Construct a new DI2CMaster::DI2CMaster object.
~DI2CMaster ()
bool isReady (void)
std::string getLastError (void)
bool writeByte (uint8_t slaveAddr, uint8_t cmdReg, uint8_t data)
Write a BYTE at specified i2c register of the slave device.
bool writeWord (uint8_t slaveAddr, uint8_t cmdReg, uint16_t data)
Write a WORD (2 bytes) at specified i2c register of the slave device.
bool writeBuf (uint8_t slaveAddr, uint8_t cmdReg, uint8_t *writeBuffer, uint16_t writeLen)
Write a BUFFER at specified i2c register of the slave device.
uint8_t recvByte (uint8_t slaveAddr)
Read a BYTE from an i2c slave device.
uint16_t recvWord (uint8_t slaveAddr)
Read a WORD(2 bytes) from an i2c slave device.
bool recvBuf (uint8_t slaveAddr, uint8_t *recvBuf, uint16_t recvLen)
Read a BUFFER from an i2c slave device.
uint8_t askForByte (uint8_t slaveAddr, uint8_t cmdReg)
Read a BYTE from specified i2c register of the slave device.
uint16_t askForWord (uint8_t slaveAddr, uint8_t cmdReg)
Read a WORD from specified i2c register of the slave device.
bool askForBuf (uint8_t slaveAddr, uint8_t cmdReg, uint8_t *recvBuf, uint16_t recvLen)
Read a BUFFER from specified i2c register of the slave device.
bool sendByte (uint8_t slaveAddr, uint8_t data)
Send a BYTE to a slave device.
bool sendWord (uint8_t slaveAddr, uint16_t data)
Send a WORD (2 bytes) to a slave device.
bool sendBuf (uint8_t slaveAddr, uint8_t *data, uint16_t dataLen)
Send a BUFFER to a slave device.
Private Attributes
uint8_t devAddr
Detailed Description
Definition at line 51 of file INA228.h.
Constructor & Destructor Documentation
INA228()
INA228::INA228 (uint8_t deviceAddr, DI2CBusHandle i2cBusHandle)
Definition at line 41 of file INA228.cpp.
References devAddr.
~INA228()
INA228::~INA228 ()
Definition at line 46 of file INA228.cpp.
Member Function Documentation
begin()
bool INA228::begin (void)
Definition at line 51 of file INA228.cpp.
References devAddr, INA228_CONFIG, INA228_SHUNT_CAL, SHUNT_CAL, and DI2CMaster::writeWord().
Referenced by main().
charge()
float INA228::charge (void)
Definition at line 153 of file INA228.cpp.
References DI2CMaster::askForBuf(), CURRENT_LSB, devAddr, and INA228_CHARGE.
Referenced by main().
current()
float INA228::current (void)
Definition at line 101 of file INA228.cpp.
References DI2CMaster::askForBuf(), CURRENT_LSB, devAddr, and INA228_CURRENT.
Referenced by main().
dietemp()
float INA228::dietemp (void)
Definition at line 73 of file INA228.cpp.
References DI2CMaster::askForWord(), devAddr, and INA228_DIETEMP.
Referenced by main().
energy()
float INA228::energy (void)
Definition at line 134 of file INA228.cpp.
References DI2CMaster::askForBuf(), CURRENT_LSB, devAddr, and INA228_ENERGY.
Referenced by main().
getInfo()
std::string INA228::getInfo (void)
Definition at line 169 of file INA228.cpp.
References DI2CMaster::askForWord(), devAddr, INA228_DEVICE_ID, and INA228_MANUFACTURER_ID.
Referenced by main().
power()
float INA228::power (void)
Definition at line 116 of file INA228.cpp.
References DI2CMaster::askForBuf(), CURRENT_LSB, devAddr, and INA228_POWER.
Referenced by main().
shuntvoltage()
float INA228::shuntvoltage (void)
Definition at line 84 of file INA228.cpp.
References DI2CMaster::askForBuf(), devAddr, and INA228_VSHUNT.
Referenced by main().
voltage()
float INA228::voltage (void)
Definition at line 58 of file INA228.cpp.
References DI2CMaster::askForBuf(), devAddr, and INA228_VBUS.
Referenced by main().
Member Data Documentation
devAddr
uint8_t INA228::devAddr private
Definition at line 67 of file INA228.h.
Referenced by begin(), charge(), current(), dietemp(), energy(), getInfo(), INA228(), power(), shuntvoltage(), and voltage().
The documentation for this class was generated from the following files:
drivers/INA228/INA228.h
drivers/INA228/INA228.cpp