My Project: examples/ddigitalio/sbc-io-demo/main.cpp File Reference
main.cpp File Reference
#include <iostream>
#include <ddigitalinput>
#include <ddigitaloutput>
Functions
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 5 of file main.cpp.
References DDigitalInput::begin(), DDigitalOutput::begin(), delay(), DGpioChip::getInfo(), DDigitalInput::getLastError(), DGpioChip::getLastError(), DGpioChip::handle(), DDigitalInput::isChanged(), DGpioChip::isReady(), LOW, DDigitalInput::read(), and DDigitalOutput::write().