My Project: src/dgpio/derrorcodes.h File Reference
derrorcodes.h File Reference
#include <lgpio.h>
#include <iostream>
#include <map>
#include <string>
Macros
#define DERR_CLASS_NOT_BEGUN -200
#define DERR_UNKOWN_PIN_MODE -201
#define DERR_GPIO_NOT_ATTACHED -202
#define DERR_GPIO_NOT_READY -203
#define DRES_OK LG_OKAY
Typedefs
typedef int DResult
Functions
static void fatal (std::string msg, int lgErrCode)
static void error (std::string msg, int lgErrCode)
static std::string getErrorCode (int lgErrCode)
Variables
static const std::map< int, std::string > DErrorCodes
Macro Definition Documentation
DERR_CLASS_NOT_BEGUN
#define DERR_CLASS_NOT_BEGUN -200
Definition at line 10 of file derrorcodes.h.
DERR_GPIO_NOT_ATTACHED
#define DERR_GPIO_NOT_ATTACHED -202
Definition at line 12 of file derrorcodes.h.
DERR_GPIO_NOT_READY
#define DERR_GPIO_NOT_READY -203
Definition at line 13 of file derrorcodes.h.
DERR_UNKOWN_PIN_MODE
#define DERR_UNKOWN_PIN_MODE -201
Definition at line 11 of file derrorcodes.h.
DRES_OK
#define DRES_OK LG_OKAY
Definition at line 15 of file derrorcodes.h.
Typedef Documentation
DResult
typedef int DResult
Definition at line 17 of file derrorcodes.h.
Function Documentation
error()
static void error (std::string msg, int lgErrCode) static
Definition at line 142 of file derrorcodes.h.
References DErrorCodes.
fatal()
static void fatal (std::string msg, int lgErrCode) static
Definition at line 132 of file derrorcodes.h.
References DErrorCodes.
Referenced by initGpio().
getErrorCode()
static std::string getErrorCode (int lgErrCode) static
Definition at line 151 of file derrorcodes.h.
References DErrorCodes.
Referenced by DHTXX::getLastError(), DDigitalInput::getLastError(), DDigitalOutput::getLastError(), DGpioChip::getLastError(), DPwmOut::getLastError(), and DServo::getLastError().
Variable Documentation
DErrorCodes
const std::map<int,std::string> DErrorCodes static
Definition at line 19 of file derrorcodes.h.
Referenced by error(), fatal(), and getErrorCode().