My Project: src/dgpio/dgpio.h File Reference
dgpio.h File Reference
#include <lgpio.h>
#include <derrorcodes.h>
#include <dgpiochip>
#include <dutils>
Macros
#define mapValue(x, in_min, in_max, out_min, out_max) (x-in_min)*(out_max-out_min)/(in_max-in_min)+out_min
#define LOW LG_LOW
#define HIGH LG_HIGH
Enumerations
enum DPinMode { INPUT , OUTPUT , INPUT_PULLUP , SOFT_PWM }
enum DPinFlags {
NO_FLAGS = 0 , ACTIVE_LOW = 4 , OPEN_DRAIN = 8 , OPEN_SOURCE = 16 ,
PULL_UP = 32 , PULL_DOWN = 64 , PULL_NONE = 128
}
Functions
DResult initGpio (int gpioDevice, DGpioHandle &handle)
Initilize gpio chip.
bool isGpioReady (DGpioHandle &handle)
Check if gpio chip is initilized.
DResult initPin (uint8_t pin, DPinMode mode, DPinFlags flags, DGpioHandle handle)
Configures a pin to be used as input, output or whatever.
int readPin (uint8_t pin, DGpioHandle handle)
Read pin level.
DResult writePin (uint8_t pin, uint8_t level, DGpioHandle handle)
Set pin level.
DResult writeAnalog (uint8_t pin, uint8_t value, DGpioHandle handle)
Output a pwm signal to pin.
DResult releasePin (uint8_t pin, DGpioHandle handle)
Free a pin that can be claimed for an other use.
DResult shutdownGpio (DGpioHandle handle)
Close handle for gpio chip.
Macro Definition Documentation
HIGH
#define HIGH LG_HIGH
Definition at line 24 of file dgpio.h.
LOW
#define LOW LG_LOW
Definition at line 21 of file dgpio.h.
mapValue
#define mapValue (x, in_min, in_max, out_min, out_max) (x-in_min)*(out_max-out_min)/(in_max-in_min)+out_min
Definition at line 18 of file dgpio.h.
Enumeration Type Documentation
DPinFlags
enum DPinFlags
Enumerator
NO_FLAGS
ACTIVE_LOW
OPEN_DRAIN
OPEN_SOURCE
PULL_UP
PULL_DOWN
PULL_NONE
Definition at line 42 of file dgpio.h.
DPinMode
enum DPinMode
Enumerator
INPUT
OUTPUT
INPUT_PULLUP
SOFT_PWM
Definition at line 41 of file dgpio.h.
Function Documentation
initGpio()
DResult initGpio (int gpioDevice, DGpioHandle & handle)
Initilize gpio chip.
Must be call once before any gpio operation.
InitPin() call it by it self
On ARDUINO return true.
Parameters
gpioDevice -> device index.
DGpioHandle -> handle from initGpio(), on ARDUINO is ignored.
Returns
true on success otherwise false.
Definition at line 14 of file dgpio.cpp.
References DRES_OK, and fatal().
Referenced by DDigitalButton::DDigitalButton(), DDigitalInput::DDigitalInput(), DDigitalOutput::DDigitalOutput(), DHTXX::DHTXX(), DPwmOut::DPwmOut(), and initPin().
initPin()
DResult initPin (uint8_t pin, DPinMode mode, DPinFlags flags, DGpioHandle handle)
Configures a pin to be used as input, output or whatever.
Parameters
pin -> gpio pin.
mode -> one of DPinMode values.
flags -> on of DPinFlags values.
DGpioHandle -> handle from initGpio(), on ARDUINO is ignored.
Returns
true on success otherwise false.
Definition at line 74 of file dgpio.cpp.
References DERR_UNKOWN_PIN_MODE, DRES_OK, initGpio(), INPUT, INPUT_PULLUP, OUTPUT, PULL_UP, and SOFT_PWM.
Referenced by DDigitalInput::begin(), DHTXX::begin(), DPwmOut::begin(), DDigitalOutput::begin(), and DDigitalButton::begin().
isGpioReady()
bool isGpioReady (DGpioHandle & handle)
Check if gpio chip is initilized.
On ARDUINO return true;
Parameters
DGpioHandle -> handle from initGpio(), on ARDUINO is ignored.
Returns
true on success otherwise false.
Definition at line 42 of file dgpio.cpp.
Referenced by DDigitalButton::DDigitalButton(), DDigitalInput::DDigitalInput(), DDigitalOutput::DDigitalOutput(), DHTXX::DHTXX(), and DPwmOut::DPwmOut().
readPin()
int readPin (uint8_t pin, DGpioHandle handle)
Read pin level.
Parameters
Pin -> gpio pin.
DGpioHandle -> handle from initGpio(), on ARDUINO is ignored.
Returns
pin level HIGH or LOW (negative number is errCode)
Definition at line 130 of file dgpio.cpp.
Referenced by DDigitalInput::read(), and DDigitalOutput::read().
releasePin()
DResult releasePin (uint8_t pin, DGpioHandle handle)
Free a pin that can be claimed for an other use.
On ARDUINO return true;
Parameters
pin -> gpio pin.
DGpioHandle -> handle from initGpio(), on ARDUINO is ignored.
Returns
true on success otherwise false.
Definition at line 199 of file dgpio.cpp.
References DRES_OK.
Referenced by DDigitalButton::~DDigitalButton(), DDigitalInput::~DDigitalInput(), DDigitalOutput::~DDigitalOutput(), DHTXX::~DHTXX(), and DPwmOut::~DPwmOut().
shutdownGpio()
DResult shutdownGpio (DGpioHandle handle)
Close handle for gpio chip.
On ARDUINO return true;
Parameters
DGpioHandle -> handle from initGpio(), on ARDUINO is ignored.
Returns
true on success otherwise false.
Definition at line 218 of file dgpio.cpp.
References DRES_OK.
writeAnalog()
DResult writeAnalog (uint8_t pin, uint8_t value, DGpioHandle handle)
Output a pwm signal to pin.
ARDUINO: PWM output only works on the pins with hardware support. See https://www.arduino.cc/reference/en/language/functions/analog-io/analogwrite/ for details.
Parameters
pin -> gpio pin.
Value -> pwm value from 0 to 255.
DGpioHandle -> handle from initGpio(), on ARDUINO is ignored.
Returns
true on success otherwise false.
Definition at line 176 of file dgpio.cpp.
References DRES_OK, and mapValue.
writePin()
DResult writePin (uint8_t pin, uint8_t level, DGpioHandle handle)
Set pin level.
Parameters
pin -> gpio pin.
level -> level: HOGH or LOW.
DGpioHandle -> handle from initGpio(), on ARDUINO is ignored.
Returns
true on success otherwise false.
Definition at line 150 of file dgpio.cpp.
References DRES_OK.
Referenced by DPwmOut::high(), DPwmOut::low(), and DDigitalOutput::write().