My Project: examples/dpwm/sbc-pwm-demo/main.cpp File Reference
main.cpp File Reference
#include <iostream>
#include <dpwm>
Functions
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 6 of file main.cpp.
References DPwmOut::begin(), DGpioChip::getInfo(), DGpioChip::getLastError(), DPwmOut::getLastError(), DGpioChip::handle(), DGpioChip::isReady(), and DPwmOut::set().