My Project: examples/dservo/sbc-servo-demo/main.cpp File Reference
main.cpp File Reference
#include <iostream>
#include <dservo>
Functions
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 4 of file main.cpp.
References DServo::begin(), delay(), DServo::getCurrPulseUs(), DGpioChip::getInfo(), DGpioChip::getLastError(), DGpioChip::handle(), DGpioChip::isReady(), and DServo::writeMicroseconds().