My Project: src/dutils/dutils.h File Reference
dutils.h File Reference
Functions
void delay (unsigned long ms)
Stops thread for milliseconds.
void delayMicroseconds (unsigned long us)
Stops thread for microsecondss.
unsigned long millis (void)
Get current timestamp in milliseconds (c++ equivalent of arduino millis()).
unsigned long micros (void)
Get current timestamp in microseconds (c++ equivalent of arduino micros()).
Function Documentation
delay()
void delay (unsigned long ms)
Stops thread for milliseconds.
Parameters
ms milliseconds to pause for.
Definition at line 12 of file dutils.cpp.
Referenced by loop(), main(), and setup().
delayMicroseconds()
void delayMicroseconds (unsigned long us)
Stops thread for microsecondss.
Parameters
ms milliseconds to pause for.
Definition at line 21 of file dutils.cpp.
micros()
unsigned long micros (void)
Get current timestamp in microseconds (c++ equivalent of arduino micros()).
Returns
unsigned long microseconds value.
Definition at line 47 of file dutils.cpp.
millis()
unsigned long millis (void)
Get current timestamp in milliseconds (c++ equivalent of arduino millis()).
Returns
unsigned long milliseconds value.
Definition at line 30 of file dutils.cpp.
Referenced by DDigitalInput::begin(), DDigitalButton::begin(), DCMotorRunTest(), DDigitalInput::isChanged(), DDigitalInput::isChangedToHigh(), DDigitalInput::isChangedToLow(), DStepper::RampRpm(), and ServoRunTest().