My Project: examples/i2c/sbc-i2c-demo/i2c-scan.cpp File Reference
i2c-scan.cpp File Reference
#include <iostream>
#include <dutils>
#include <di2c>
#include <dmpacket>
Functions
void showUsage (std::string binaryName)
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 20 of file i2c-scan.cpp.
References DI2CBus::devices, DI2CBus::getInfo(), DI2CBus::getLastError(), DI2CBus::SCAN_MODE_READ, DI2CBus::SCAN_MODE_WRITE, DI2CBus::scanForDevices(), and showUsage().
showUsage()
void showUsage (std::string binaryName)
Definition at line 6 of file i2c-scan.cpp.
Referenced by main().