My Project: examples/i2c/sbc-i2c-demo/ina228.cpp File Reference
ina228.cpp File Reference
#include <iostream>
#include <dutils>
#include <INA228/INA228.h>
Functions
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 5 of file ina228.cpp.
References INA228::begin(), INA228::charge(), INA228::current(), delay(), INA228::dietemp(), INA228::energy(), INA228::getInfo(), DI2CBus::handle(), INA228::power(), INA228::shuntvoltage(), and INA228::voltage().