My Project: examples/i2c/sbc-i2c-demo/ina226.cpp File Reference
ina226.cpp File Reference
#include <iostream>
#include <dutils>
#include <INA226/INA226.h>
Functions
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 5 of file ina226.cpp.
References INA226::begin(), INA226::current(), delay(), INA226::getInfo(), DI2CBus::handle(), INA226::power(), and INA226::voltage().